### ISSUE TITLE
Support for Italian fiscal code

### ISSUE THREAD

**Issue by supix** [bchavez/Bogus#109]
It might be useful to add routines to deal with Italian fiscal code, according to [its rules](https://en.wikipedia.org/wiki/Italian_fiscal_code_card). Fiscal code is currently the main citizen identification code in Italy (always assigned on birth).

The simplest method might be like this:

```csharp
/// <summary>
///   Generates an Italian Fiscal Code
/// </summary> 
public string ItalianFiscalCode() -> GRGTSF86T55R342Y
```

Italian fiscal code is generated starting from
- firstname
- lastname
- sex
- date of birth
- country of birth

and its last character is a checksum. Then, in order to preserve Person context, it might have sense to implement more method overloads:

```csharp
/// <summary>
///   Generates an Italian Fiscal Code
/// </summary>
/// <param name="validChecksum">
///   Indicates whether the generated Fiscal Code has a valid checksum or not
/// </param>
public string ItalianFiscalCode(bool validChecksum = true)

/// <summary>
///   Generates an Italian Fiscal Code
/// </summary>
/// <param name="minAge">Minimum age of the holder</param>
/// <param name="maxAge">Maximum age of the holder</param>
/// <param name="validChecksum">
///   Indicates whether the generated Fiscal Code has a valid checksum or not
/// </param>
public string ItalianFiscalCode(int minAge, int maxAge, bool validChecksum = true)

/// <summary>
///   Generates an Italian Fiscal Code
/// </summary>
/// <param name="lastName">Last name of the holder</param>
/// <param name="firstName">First name of the holder</param>
/// <param name="birthday">Birthday of the holder</param>
/// <param name="maleSex">Indicates whether the holder is male</param>
/// <param name="validChecksum">
///   Indicates whether the generated Fiscal Code has a valid checksum or not
/// </param>
public string ItalianFiscalCode(string lastName, string firstName, DateTime birthday, bool maleSex, bool validChecksum = true)
```

If this extension is acceptable, I'm available to take in charge the implementation.

Regards.

**Comment by bchavez** [comment]
Hi Marcello,

You have a great idea. I'd be happy to accept a PR for adding Italian fiscal codes. I recently added `Gender` as a field on `Person` in cf8b0d2 to help you implement this feature.

Previously we didn't have `Gender` on `Person` mostly because the default `en` first & last name dataset were not organized based on gender, but the most recent update with faker.js now has names organized by gender, so it makes some sense to have a `Gender` field in `Person` now.

As for where your extension code should go:

* I think the best place would probably be inside the [`Bougs\Extensions`](https://github.com/bchavez/Bogus/tree/master/Source/Bogus/Extensions) folder.
* You can make a new file `ExtensionsForItaly.cs` and write your `FiscalCode` generator.
* You can follow [`ExtensionsForBrazil.cs`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Extensions/ExtensionsForBrazil.cs) as a really good example.

As for the API:
* Is `ItalianFiscalCode` the most common in Italy? or is `CodiceFiscale` better? I think you should pick a method name that is the most friendly for Italian locale/culture (ignoring English).
  For example, [**Finland**](https://github.com/bchavez/Bogus#api-extension-methods) has `.Henkilötunnus()` method for identification numbers in **Finland**. I know it's a weird but I think people feel happy when they see Bogus APIs contain method names that are part of their home culture.

  Here's a list of the other local-specific extension methods:
  https://github.com/bchavez/Bogus#api-extension-methods

* Having an extension method hang off `Person` where `Person.CodiceFiscale(validChecksum = true)` would be good.
* Also, if you want to have an extension method that hangs off `Finance` for more fine-grained parameters, that's okay too. IE:

```csharp
//Extend the Person class with FiscalCode
public string FiscalCode(this Person p, bool validChecksum = true){
  // generate fiscal code using context Person: p.FirstName, p.LastName, p.Age, etc...
}

//Extend the Finance data set with more fine-grained parameters
public string FiscalCode(this Finance finace, string lastName, string firstName, DateTime birthday, bool maleSex, bool validChecksum = true){
  // generate fiscal code using parameters passed in.
}
```
* Your fiscal code tests should probably go inside [`PersonTests.cs`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/PersonTest.cs).

I think you're good to go now. Have some fun! I really look forward to your pull-request Marcello!

Thanks,
Brian

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***

**Comment by supix** [comment]
I Bogus. Thanks for the useful information.

I went for `CodiceFiscale()`.
Thanks for adding gender to Person class. Useful for this routine.
I'm going to submit this pull request. As you can read from commit messages, there are two new extension methods for Person and Finance, exactly according to your suggestion.

Not sure if I have to update README.md as well (in order to describe new extensions). It seems to me that this file is somewhat automatically generated. In case, let me know.

Thanks a lot.
Marcello.
