### ISSUE TITLE
Populate not ignoring ignored properties in a ruleset

### ISSUE THREAD

**Issue by Mardoxx** [bchavez/Bogus#121]
```cs
            public class TestObject
            {
                public Guid Id { get; set; }
                public string Name { get; set; }
            }

            [Fact]
            public void Test()
            {
                var faker = new Bogus.Faker<TestObject>()
                    .StrictMode(true)
                    .RuleFor(x => x.Id, Guid.NewGuid)
                    .RuleFor(x => x.Name, x => x.Person.FirstName)
                    .RuleSet("update", f => f.Ignore(x => x.Id));

                var obj = faker.Generate();

                var id = obj.Id; // value copy
                var name = obj.Name; // value copy

                faker.Populate(obj, "default,update");

                Assert.True(id == obj.Id); // fails
                Assert.False(name == obj.Name);
            }
```

I'd expect this to build up using "default" ruleset, then override any from "update" ruleset (etc..)

Expected result should be `TestObject` retains its `Id` and has a new `Name` assigned.

**Comment by bchavez** [comment]
Hi @Mardoxx ,

Hm. This looks like a bug. I'll have to take a closer look when I get a little more time later today.

Thank you for reporting the issue. I really appreciate it.

Brian

:evergreen_tree: :crystal_ball: **[PINES - Fate](https://www.youtube.com/watch?v=M2D7lCeVxGs)**

**Comment by Mardoxx** [comment]
I think here https://github.com/bchavez/Bogus/blob/8d753628c51df17ee22a718f0bc0333ca2e6cb9b/Source/Bogus/Faker%5BT%5D.cs#L442-L446

It wants to build up a list of actions, overwriting as it moves through the rulesets, instead of applying them sequentially?

I don't _think_ this would break existing functionality either?

**Comment by bchavez** [comment]
roughly yes, that's where i was looking. but after thinking about the
problem more, my thoughts are to refactor and make ignore rules empty
actions instead of keeping track of two disjoint sets of the ignore &
actions.

its a bit more elegant and should simplify the internals a bit more and
make the simple case work:
```
.RuleFor(x=>x.Name, .... )
.Ignore(x=>x.Name)
```

**Comment by Mardoxx** [comment]
Ah right! Yes that sounds good 😄

**Comment by bchavez** [comment]
Hi @Mardoxx ,

Finally had some time to study your issue. Just want to say thank you for posting some sample code I could work with. It really helps to understand what you are trying to achieve with **Bogus**.

So, I did the refactor in e8bfefc4ebd50ec8ac7f936e29790c174d66c706:

First, e8bfefc4ebd50ec8ac7f936e29790c174d66c706 primarily fixes the inability to ignore a property or field after a rule had already been set. IE: The following code perviously didn't work, but now it does:  https://github.com/bchavez/Bogus/blob/e8bfefc4ebd50ec8ac7f936e29790c174d66c706/Source/Bogus.Tests/GitHubIssues/Issue121.cs#L71-L80

**Bogus** [`v22.0.2`](https://www.nuget.org/packages/Bogus/22.0.2) cointains this fix. Should be available on NuGet soon: https://www.nuget.org/packages/Bogus/22.0.2

----

Second, it turns out e8bfefc4ebd50ec8ac7f936e29790c174d66c706 doesn't enable your scenario as elegantly as we'd like. As you've correctly identified, `RuleSets` are applied sequentially. So, `faker.Populate(obj, "default,update");` will apply all `default` rules, then `update` rules thereafter. Essentially, when a `RuleSet` is defined, the `RuleSet` is an empty set of rules that need to be built up. In your case, the `update` set variable doesn't inherit or override any rules from the `default` set:
```csharp
var faker = new Faker<TestObject>()
     .StrictMode(true)
     .RuleFor(x => x.Id, Guid.NewGuid)
     .RuleFor(x => x.Name, x => x.Person.FirstName)
     .RuleSet("update", set =>
        {
           set.Ignore(x => x.Id);
        });
```
`set.Ignore(x => x.Id);` just hangs off all alone and it doesn't "override" the `.RuleFor(x => x.Id, Guid.NewGuid)` in the `default` rule set. We don't precompute or "merge" the `default + update` rulsets for a final set of rules before applying them.

I think the primary reason for running rules sequentially is in preserving deterministic outputs with **Bogus**. Straightforward determinism is an important concept in **Bogus**.

I'm sure yet if this existing behavior should change. I'm guessing someone out there is relying on this merge-less/sequential behavior of `RuleSet`. Personally, I need more time to think about the implications of such a change. Also, if others stumble across the same expectations you have about `RuleSet` that will probably motivate me to change the current behavior. But as it stands now, I'm more reluctant to change the existing behavior.

For now, though, I hope the following workaround can help with your scenario:

https://github.com/bchavez/Bogus/blob/e8bfefc4ebd50ec8ac7f936e29790c174d66c706/Source/Bogus.Tests/GitHubIssues/Issue121.cs#L43-L65

I know it's not ideal, but it should work in the most recent update: [`Bogus v22.0.2`](https://www.nuget.org/packages/Bogus/22.0.2). Basically, with the help of the `.Clone()` method, you'll need to maintain 2 fakers, a **generator faker** and an **update faker** and use them accordingly. In a nutshell, using the `.Clone()` method, is more of a clear-cut way to copy around the rule state of `Faker<T>`.

I thought about adding additional methods on `IRuleSet` that would enable copying of rules from other rulesets like:
```csharp
var faker = new Faker<TestObject>()
     .StrictMode(true)
     .RuleFor(x => x.Id, Guid.NewGuid)
     .RuleFor(x => x.Name, x => x.Person.FirstName)
     .RuleSet("update", set =>
        {
           set.CopyFrom("default")
           set.Ignore(x => x.Id);
        });
```
But then we start going down this road where rules start becoming hard to maintain, reason-about, difficult to debug, and difficult to discern sequential/deterministic behavior.

---

On an ending note, if you *really* want your precomputed rule set behavior, you can re-implement [`PopulateInternal`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Faker%5BT%5D.cs#L418) in a derived `class Faker2<T> : Faker<T>`. `PopulateInternal` is `protected virtual` and pretty much all the internals of `Faker<T>` are exposed to derived classes. If there's anything you need access to please feel free to comment or send a PR. I have no qualms about opening up the internals of everything to inheritors. I've mostly taken the view that anyone who inherits knows what they're doing and is probably trying to achieve something that I fail to provide.

I hope the workarounds I've provided above are sufficient.

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***
