### ISSUE TITLE
NodaTime support

### ISSUE THREAD

**Issue by ashrafxcoder** [bchavez/Bogus#122]
It would be better if noda time date support is added to faker.

**Comment by bchavez** [comment]
Hi @ashrafxcoder ,

Thank you for the feedback. I really appreciate it.

I agree it would be pretty sweet to have **Bogus** generate **NodaTime** types. But, turns out though, that means we'd need a direct dependency on the **NodaTime** library. 

A key design goal for the **Bogus** library is to keep the number of dependencies to a minimum. In the past, we've had various issues *depending* on other third-party libraries (issue #89 comes to mind). In addition, third-party dependencies create maintenance headaches like #2 and #3.

So... as far as having direct support for **NodaTime** in the main `Bogus` **NuGet** package that would be a ***no*** but that doesn't preclude us from having an extension **NuGet** package like `Bogus.Extensions.NodaTime`. If you're interested starting or helping out with that, let me know.

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by bchavez** [comment]
Excellent work Simon! Thanks for knocking that out.

I added your extension to the [README](https://github.com/bchavez/Bogus#amazing-community-extensions) page.

Going to close down the issue now since Simon's extension looks like it fixes this issue.

Thanks again everyone!
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
