### ISSUE TITLE
Unable to increase performance of Bogus in multithreaded environment

### ISSUE THREAD

**Issue by Umkerius** [bchavez/Bogus#125]
Hello, guys!

I'm generating dataset with complex structure by using of Bogus. This structure looks similar to tree: I can generate data subsets independently, so I tried to use multithreading for increase of performance.
Unfortunately, performance was decreased. The giant lock in Faker<>.PopulateInternal is the reason:
lock( Randomizer.Locker.Value ) { ... }
PopulateInternal is the main method in generation routine and Randomizer.Locker is static field, so no way to workaround exists.

Could you please tell me is this giant lock is really necessary? 
In my opinion, lock granularity in PopulateInternal should be totally desreased: Faker class already use non-static Randomizer for randomization.

**Comment by bchavez** [comment]
Hi Andrew,

The primary reason for locks inside **Bogus** is to gain some level of sanity when generating data sets in a deterministic way.

We've had problems with in the past (#12, #46) because we previously had a lax view of threading.  People who set seed values usually expect to generate a repeatable & deterministic sequence of values for their unit tests. It is a bit strange when this doesn't work out of the box for various reasons under various scenarios when using **Bogus**.

But more fundamentally, **.NET**'s `Random` class is not thread-safe.
See: https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx#ThreadSafety

Quote from MSDN:
> Instead of instantiating individual Random objects, we recommend that you create a single Random instance to generate all the random numbers needed by your app. However, Random objects are not thread safe. If your app calls Random methods from multiple threads, you must use a synchronization object to ensure that only one thread can access the random number generator at a time.

**Bogus** is inline following Microsoft's guidance and advice in this regard. In the MSDN example, Microsoft also uses `lock(randLock)` for multi-threaded access to the `Random` class. If you don't use locks, multiple threads can draw the same number at the "same time" which essentially defeats the purpose of the `Random` class.

Imagine running a unit test and generating 10 objects that look exactly the same on 10 threads. Then the next unit test run only 5 of those 10 objects on 10 threads look the same because there just happened to be some additional scheduler latency on the last unit test run. This really turns into an indeterministic hellscape scenario.

So, **Bogus'** use of locks brings some level of sanity to issues like this. Deterministic outputs from **Bogus** are important. IE: being able to draw the same sequence of random data for a given seed is important (see #104, #100, #102).

If you don't want this locking behavior in **Bogus**, there are a few things you can do:
* See if any ideas inside #100 can help you.
* See if there's a way to run your generator program in multiple processes instead of multiple threads.
* Look at deriving your own `FastFaker<T> : Faker<T>` and overriding `PopulateInternal` with your own implementation without the lock. Copy and paste should do: https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Faker%5BT%5D.cs#L418-L475
* Fork the **Bogus** source and remove all the locking code in `Faker<T>` and `Randomizer`. It should be fairly easy to remove since the locks are only taken sparingly in a few places. IIRC, the locks are normally only taken on critical API access to the `Random` class. However, if you take this route, just know, all bets are off and threading issues we've had in the past will probably come back.

There may be a time and place in the future where we remove the need for locks, but as of right now we still support the `Randomizer.Seed` static property.

Hope that helps,
Brian

:running: :sunrise_over_mountains: ***[And I ran. I ran so far away. I just ran. I ran all night and day. I couldn't get away...](https://www.youtube.com/watch?v=0_Pq0xYr3L4)***

**Comment by Umkerius** [comment]
Hi, Brian!

Thank you for a good answer! Now I see the logic. 
If I get you right, the giant lock prevent indeterministic order of dataset generation in multithreaded environment. Even if global randomizer will replaced on local for each Faker, we cant guarantee determitistic execution.
I think, if randomizer will be threadlocal it can be trully deterministic. What do you think?

**Comment by Umkerius** [comment]
But maybe it is not very good idea: two parallel threads may use two randomizers with equivalent states which will produce the same results. I'll think about this problem

**Comment by bchavez** [comment]
Hi Andrew,

Mostly, yes, the locks inside **Bogus** are to prevent indeterministic execution from occurring in various testing environments. As an example, in unit test frameworks like **Xunit** tests are run in parallel by default.  So, I've taken some care in making **Bogus** ***just work*** out of the box as best as I can so that **Bogus**' behavior isn't totally broken.

There are two major locks in **Bogus**. The one you see in `Faker[T].cs : PopulateInternal()` and the one inside `Randomizer.cs`.
* The `lock()` in `Randomizer` mostly follows MSDN guidelines regarding thread-safety and is straightforward.
* The `lock()` in `Faker[T].cs : PopulateInternal()` is the bigger lock and prevents the indeterministic execution of rules that can possibly execute out of order in different threads. This giant lock also protects multi-threaded access to the global static `Randomizer.Seed` `Random` object.

More specifically, suppose you have the following `Faker<T>` setup:
```
var faker = new Faker<Bar>()
   .RuleFor(b => b.Id, f => f.Random.Uuid())          // 1
   .RuleFor(b => b.Email, f => f.Internet.Email())    // 2 
   .RuleFor(b => b.Name, f => f.Name.FirstName())     // 3
   .RuleFor(b => b.LastName, f => f.Name.LastName()); // 4
```
Imagine you have 3 threads, each with a reference to `var faker`, and all 3 threads execute `.Generate()` at the same time. Threads A, B, and C begin executing rules:
* Thread A executes rules 1, 2, and 3.
* Thread B executes rules 1 and 2.
* Thread C executes rule 1.
* Thread A and B are suspended.
* Thread C races to execute 2 and 3.
* Thread C suspends having executed 1, 2, and 3.
* Thread A resumes, executes rule final rule 4.
* Thread B resumes, executes rule 3, and final rule 4.
* Thread C resumes and executes final rule 4.
* Threads A, B and C are now done.

Note that the thread execution of rules is just one permutation in which threads can execute rules of `faker`. The scheduling of threads on the CPU can't be controlled and for all intents and purposes is indeterministic from userland. The giant lock in `PopulateInternal` mitigates this issue and gives some assurance that a single thread ***will*** execute the rules serially, in order, as defined, no matter the environment **Bogus** is being used in. As I mentioned earlier, locks bring some level of sanity to the issue.

Additionally, another problem, I think, is mostly due to the legacy support of the static `Randomizer.Seed` property. Given the Thread execution permutation in my previous example, a single `Random` static object source combined with out of order execution can draw a different sequence of randomness. It's similar to three people drawing cards from a single shuffled deck, the order in which people draw cards will determine the hand for each person.

If I could re-write **Bogus** again I'd leave out the static property, but oh well, c'est la vie. I don't want to change it now because it would be a big breaking change. There are a lot of **Bogus** users today including people at **Microsoft** and **Elastic Search** and they all tend to rely on `Randomizer.Seed`. Plus, I don't have much free/unpaid right now time to do extensive testing on a big change like that.

----

So, I think the best way, currently, to achieve greater performance out of **Bogus** is to:
1. Remove the bigger `PopulateInternal` lock by deriving your own faker as I mentioned above:
> Look at deriving your own `FastFaker<T> : Faker<T>` and overriding `PopulateInternal` with your own implementation without the lock. Copy and paste should do: https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Faker%5BT%5D.cs#L418-L475

2. Once you have removed the lock in your copy/paste override, use `.Clone()` and `.UseSeed(n)` methods as described in #100:

https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/GitHubIssues/Issue100.cs#L148-L167

```
var faker = new FastFaker<Bar>()
   .RuleFor(b => b.Id, f => f.Random.Uuid())
   .RuleFor(b => b.Email, f => f.Internet.Email())
   .RuleFor(b => b.Name, f => f.Name.FirstName())
   .RuleFor(b => b.LastName, f => f.Name.LastName());

var fakes = ParallelEnumerable.Range(1, 5000)
   .Select(n =>
      faker
         .Clone()
         .UseSeed(n)
         .Generate(1000).ToArray()
   ).ToArray();
```
The `.Clone()` method will clone the internal state of a `Faker<T>` to avoid variable contention. The `.UseSeed(n)` method lets you set a local `Randomizer` inside the cloned `Faker<T>` instance (similar to `ThreadLocal`). With the unlocked & overridden `PopulateInternal` and `.Clone/.UseSeed` you should be able to squeeze more performance out of **Bogus**.

Please try that and let me know how it goes. If that doesn't work, I dunno, I'm pretty much out of ideas.

Thanks,
Brian

:dizzy: :boom: **[Chaos Chaos - Do You Feel It?](https://www.youtube.com/watch?v=MH17AHIklCM)**
