### ISSUE TITLE
can I use this package for .net core?

### ISSUE THREAD

**Issue by A-Programmer** [bchavez/Bogus#128]
Hello.
Can i use this package in asp.net core mvc?

**Comment by bchavez** [comment]
Hi @A-Programmer ,

Yes,**Bogus** will work with **.NET Core** since **Bogus** supports **.NET Standard 1.3**.

Additionally, you can use it in **ASP.NET Core MVC**. If you have more questions, feel free to ask on our Gitter.IM chat channel here: https://gitter.im/bchavez/Bogus

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)
