### ISSUE TITLE
[Question] RuleFor code generating for all properties

### ISSUE THREAD

**Issue by idubnori** [bchavez/Bogus#129]
Is there any Intellisence / Roslyn extensions or other solutions?

Something like the below.
Generate `RuleFor` code rows for all public properties.
`Property` expression parameter is generated as each target class' property.
`Setter` expression parameter is generated as default or custom rule-based by type or property name.

**Comment by bchavez** [comment]
Hi @idubnori ,

Thanks for your question. I appreciate it.

No, we don't have any **Roslyn** analyzer that can code-gen `RuleFor`s on `Faker<T>` given public property/fields of `T`. Although, that would be pretty sweet if we had something like that.  You have a really great idea and it is worth exploring.

Currently, the closest thing we have to auto generating rules is Nick Dodd's [**`AutoBogus`**](https://www.nuget.org/packages/AutoBogus/) **NuGet** package.

Hope that helps,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by idubnori** [comment]
Hi Brian,

Thank you for kindly teaching me that. I might be going on a Roslyn analyzer journey.

[**Kimiko Kasai - Vibration (Love Celebration)**](https://www.youtube.com/watch?v=v7RpDr7njC0)

**Comment by bchavez** [comment]
### Proof of concept, Bogus auto-rule, code generation in Visual Studio: :sunglasses: 

![untitled](https://user-images.githubusercontent.com/478118/36710841-432326c0-1b35-11e8-9ea2-a83191ede1af.gif)


:+1: :v: ***["Because we can, can, can... Yes we can, can, can, can..."](https://www.youtube.com/watch?v=rjIl_xFUruM)***

**Comment by idubnori** [comment]
@bchavez 

Wow! Super great!
I was swimming in a SyntaxFactory expression pond for indenting `RuleFor`...
Also, I was considering the proper notification position. it might not  be `new` token.
Anyway, cant wait this release. :smile:

**Comment by bchavez** [comment]
Hi @idubnori ,

Yea, I was thinking the same. I moved the notification position under the `Faker` position for now. Another good position candidate was the last `.RuleFor` syntax node in the method chain.

I'm getting close to releasing the analyzer, putting the final touches on the release. Should be soon.

Also, I decided to make this analyzer tool part of a premium package that I've been working on for a few months now. The **Bogus Premium** license package contains extended data sets like `Bogus.Healthcare` and `Bogus.Automotive` that lets you generate fake medical records, illnesses, diagnosis, car make/model, etc...

The premium package isn't part of the open-source project here. The premium project is under a different license and inside a private repository. 

However, I want to offer you a free perpetual license for the premium package since the analyzer/codefix was your idea. So, send me an email at bchavez@bitarmory.com and [post the SHA-512 hash](https://www.cleancss.com/sha512-hash-generator/) of your email address here so I know it's you. Alternatively, posting your public [GPG/PGP](https://www.gpg4win.org/) key works too. :sunglasses: 

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Comment by idubnori** [comment]
@bchavez 

Thank you so much for giving me it with your good intentions!
I wanted to study your the code fix implementation, however, looks good decision.

I've sent to an email to you, and my address hash is `97f1d8db12200ad73286842436e5989850814ec8eaca8c5c4251fffba38c73248b4f5952b52e85566a97a66d2808a8b39c2af0b6852159156fdcc05eaaeb412a`

Thanks,
idubnori

**Comment by bchavez** [comment]
Hey @idubnori , going to close this issue now, **Bogus Premium** has been released. :+1: 

https://github.com/bchavez/Bogus#bogus-premium-extensions

Thanks and take care,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)
