### ISSUE TITLE
Faker to handle bar expreession

### ISSUE THREAD

**Issue by StefDotmailer** [bchavez/Bogus#134]
Would be nice to have the reverse function of `Faker.Parse`

Once defined a Faker, it is useful to store its rules as text and modify and reload at run-time.

Thanks.

**Comment by bchavez** [comment]
Hi @StefDotmailer,

Thank you for taking the time to post your suggestion.

To better understand what you're asking for:
* Could you give a few concrete examples? A detailed explanation of your use-case scenario would help.
* Can you post some sample code on how you might use a feature like this?

Once I have a better understanding of what you're trying to do, I can make a decision if this is something that should be in **Bogus**.

Thanks,
Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by bchavez** [comment]
Hi Stef,

Thank you for the further explanation. It helps me a lot understanding what you're trying to achieve. I think I understand a little more of what you are asking for now.

If you're looking for the ability to be able to load `Faker<T>` handlebar rules from a text file, you can derive a custom `Faker<T>` with a simple method that parses handlebar rules for each member of `T`.

Here is an example:
```csharp
public class HandlebarFaker<T> : Faker<T> where T : class
{
   public HandlebarFaker<T> LoadRulesFromString(string rules)
   {
      var lines = rules.Split(
         new[] {"\r\n", "\r", "\n"}, StringSplitOptions.RemoveEmptyEntries);
         .Where( s => !s.IsNullOrWhiteSpace());

      foreach( var line in lines )
      {
         var parts = line.Split(',');
         var memberName = parts[0].Trim();
         var handlebarRule = parts[1].Trim();

         this.RuleFor(memberName, f => f.Parse($"{handlebarRule}"));
      }

      return this;
   }
}
```

Then use it like this:
```csharp
public class Foo
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public string StreetAddress { get; set; }
}

[Fact]
public void can_make_rules_from_string()
{
   var rulesFromTextFile =
      @"
         FirstName, {{name.firstName}}
         LastName, {{name.lastName}}
         StreetAddress, {{address.StreetAddress}}
      ";

   var faker = new HandlebarFaker<Foo>()
      .LoadRulesFromString(rulesFromTextFile);

   var foo = faker.Generate();

   foo.FirstName.Should().Be("Lee");
   foo.LastName.Should().Be("Brown");
   foo.StreetAddress.Should().Be("6439 Lindsey Cape");
}
```

You can find the [full working unit test here](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/GitHubIssues/Issue134.cs).

The internal methods and internal variables of `Faker<T>` are very open to derived classes. This was an intentional design decision to allow custom edge cases such as this.

I don't immediately foresee this `Faker<T>` handlebar loading feature being part of the public API for `Faker<T>` primarily because, to me, this feels like an edge case scenario. Also, I think the appropriate approach for your use case is to derive from `Faker<T>`.

Additionally, `f.Parse(...)` of handlebar rules only support `string` return types. Handlebars are also somewhat limited in the sense that they cannot call dataset methods that require/contain parameters. IE: `{{name.firstName(Gender.Female)}}` is not possible with the current tokenizer. So, adding a feature like this to the public API could cause a lot of issues.

I will keep your scenario in mind. If we get a lot of demand for a feature like this, then maybe we could add it in the future. However, until then, I think this scenario fits best as a derived `Faker<T>`.

Hope that helps,
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
