### ISSUE TITLE
Support for immutable objects

### ISSUE THREAD

**Issue by isaacabraham** [bchavez/Bogus#143]
When working with F# Records, the typical `Faker<MyRecord>().Rules()` mechanism doesn't work so well. I'd like to propose a couple of alternatives:

1. Create an alternative to the Rules() method to work with just the faker being supplied, and you have to return a T object using the faker e.g. instead of

```fsharp
type PersonDto() = 
  member val FirstName = "" with get, set
let generator =
    Bogus
        .Faker<PersonDto>()
        .Rules(fun f a -> a.FirstName <- f.Name.FirstName())
```

how about

```fsharp
type PersonDto = { FirstName : string }

let generator =
    Bogus
        .Faker<PersonDto>()
        .Rules(fun f -> { FirstName = f.Name.FirstName() })
```

This fits much better with the F# immutable objects story.

2. An alternative would be to simply surface the Faker datasets themselves. I couldn't (in my 10 minutes of experimenting - so maybe there's a way to do this) get a handle to the faker methods directly without going through the whole `Faker<_>.Rules()` thing. I'd like to just have static access to those classes if possible, which would allow for us to use them without needing to go via Rules etc.. Is there a way to do this already?

Thanks!

**Comment by bchavez** [comment]
Hi @isaacabraham ,

Thank you for submitting an issue. I really appreciate it. I always like hearing feedback (positive or negative) since it gives us a chance to make **Bogus** better.

You're right, that does look a bit clunky with F# records.

Regarding **No.2**, **Bogus** does surface the data sets in a `Faker` facade. Here's how you could use it with your **No.2** strategy:

```fsharp
type PersonDto = { FirstName : string }

let f = new Faker();
//if you want the actual dataset, not facade
//this works too
//let names = new Bogus.DataSets.Name();

let generator() = 
   { FirstName = f.Name.FirstName() }
   
generator() |> Dump |> ignore
generator() |> Dump |> ignore
generator() |> Dump |> ignore
```
![linqpad_1617](https://user-images.githubusercontent.com/478118/40131001-74710120-58ed-11e8-9065-43547dac9a71.png)

Does this solution work for you?

Going the **No.1** route might be a little more subtle in **C#** semantically since calling `.CustomInstantiator(f => return new object)` could potentially conflict semantically with `Rules(f => return new object)`. Which `new object` do I pick? Ultimately, I'd have to pick one object from both methods or throw if both were called on the same `Faker<T>`. Currently, only `.CustomInstantiator` can return a new object of `T` for use by `Faker<T>` and the rest of the call chains. If you **really**, ***really*** think **No.1** should be supported for **F#** usage I'll consider it.

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***

**Comment by bchavez** [comment]
Actually, thinking about the problem a little more, you can get **No.1** to work with the current release too. Just need to rely on `.CustomInstantiator` instead of a nicely named `.Rules`. Here's how:

```fsharp
type PersonDto = { FirstName : string }

let generator =
    Bogus
        .Faker<PersonDto>()
        .CustomInstantiator(fun f -> { FirstName = f.Name.FirstName() })
   
generator.Generate() |> Dump |> ignore
generator.Generate() |> Dump |> ignore
generator.Generate() |> Dump |> ignore
```
Let me know.

Thanks,
Brian

:thought_balloon: :mag: ***["I want to know... what you're thinking..."](https://www.youtube.com/watch?v=ijAYN9zVnwg)***

**Comment by isaacabraham** [comment]
Ok - both of them work! Thank you! One last question - `IndexGlobal` returns 0 for the first **two** records e.g.

```fsharp
type PersonDto =
  { Id : int
    FirstName : string
    LastName : string }

let generator =
    Faker<PersonDto>()
        .CustomInstantiator(fun f ->
            { Id = f.IndexGlobal
              FirstName = f.Name.FirstName()
              LastName = f.Name.LastName() })

generator.Generate(100)
|> Seq.toArray
```

gives back

```fsharp
[|{Id = 0;
     FirstName = "Garry";
     LastName = "Daugherty";}; {Id = 0;
                                FirstName = "Aniya";
                                LastName = "Davis";}; {Id = 1;
                                                       FirstName = "Jabari";
                                                       LastName = "Deckow";};
    {Id = 2;
     FirstName = "Cary";
     LastName = "Fritsch";}; {Id = 3;
                              FirstName = "Patrick";
                              LastName = "Ondricka";};
```

and if you use the first approach e.g.

```fsharp
let f = Faker()
[ for i in 1 .. 100 ->
    { Id = f.IndexGlobal
      FirstName = f.Name.FirstName()
      LastName = f.Name.LastName() } ]
```

then it's always 0.

**Comment by bchavez** [comment]
Hi @isaacabraham ,

For the first approach, when the `Faker` facade is used by itself, alone, the `f.IndexGlobal` and `f.IndexFaker` index are not automatically incremented. 

The reason for this is that both indexes (`IndexGlobal` and `IndexFaker`) are directly related to the `Faker<T>.Generate` method because that's how we know when `T` is created (and consequently when to increment the indexes).

However, when `Faker` fascade is used alone as in the first approch, there is no meaning of when a `T` is "generated".

I think that's still okay because I would change the first approach to use `i` in the **F#** list comprehension:

```fsharp
let f = Faker()

[ for i in 1 .. 10 ->
    { Id = i
      FirstName = f.Name.FirstName()
      LastName = f.Name.LastName() } ]
      |> Dump |> ignore
```
![linqpad_1619](https://user-images.githubusercontent.com/478118/40140903-eb6aa63a-5908-11e8-8ed3-c6d674dec088.png)

----------

As for the first **two** zeros in your `Faker<T>` record type example, I'll have to investigate. ***That*** does look like a bug in both **F#** and **C#**.

```csharp
void Main()
{
  var faker = new Faker<PersonDto>()
           .CustomInstantiator( f =>
               {
                  var o = new PersonDto();
                  o.Id = f.IndexGlobal;
                  o.FirstName = f.Name.FirstName();
                  o.LastName = f.Name.LastName();
                  return o;
                 });
   faker.Generate(5).Dump();
}

public class PersonDto
{
   public int Id;
   public string FirstName;
   public string LastName;
}
```
![linqpad_1620](https://user-images.githubusercontent.com/478118/40141470-e7be52be-590a-11e8-8650-00f1f0ebe10d.png)

I'll let you know what I find.

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by isaacabraham** [comment]
Indeed, this is exactly what I've done re: list comprehension. Happy to close this - probably best to raise a separate bug / issue for the duplicate 0 thing.

Thanks again.

**Comment by bchavez** [comment]
Hey @isaacabraham , 

I pushed a new version of [**`Bogus v22.0.9`**](https://www.nuget.org/packages/Bogus/22.0.9) with the bug fix. The duplicate 0 bug should be fixed now, both in **F#** and **C#**. 

![linqpad_1626](https://user-images.githubusercontent.com/478118/40203991-e4b62d36-59db-11e8-813d-b4c6ffa1d729.png)

![linqpad_1627](https://user-images.githubusercontent.com/478118/40204101-3e7b29ca-59dc-11e8-80e3-625a6d1fb37e.png)

Thanks again for your inital report.

Have a great rest of the week,
Brian

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
