### ISSUE TITLE
RuleSets and FinishWith

### ISSUE THREAD

**Issue by StefanHaug** [bchavez/Bogus#145]
Using FinishWith together with RuleSets don't work.

.RuleSet("email", r =>
{
   r.RuleFor(x=>x.Value, f => f.Internet.Email());
   r.FinishWith((f,c) => c.Type = "Test"); // <== Works
}
.FinishWIth((f,c) => c.Something = "Else") // <== Doesn't work

I was thinking of using the FinishWith to fake properties that are common across all rulesets.

**Comment by bchavez** [comment]
Hi Stefan,

Thank you for posting your issue. Are you including `default` in the rule set? By default, the `default` rules won't run unless it is included when supplying the rule sets to run. See `line 10` in the example below. Seems to be working for me:
```csharp
 1  void Main()
 2  {
 3    var faker = new Faker<Foo>()
 4    .RuleSet("email", set =>{
 5       set.RuleFor(foo => foo.Value, f => f.Internet.Email());
 6       set.FinishWith((f, c) => c.Type = "Test" );
 7     })
 8     .FinishWith((f, c) => c.Something = "Else");
 9    
10   var sample = faker.Generate("email,default");
11   sample.Dump();
12  }

public class Foo{
   public string Value{get;set;}
   public string Type{get;set;}
   public string Something {get;set;}
}
```
![linqpad_1676](https://user-images.githubusercontent.com/478118/40645833-56d0bd56-62dc-11e8-9426-3a245e8d5e65.png)

If you still find issues with `FinishWith` rules running feel free to re-open the issue with a more complete example for me to test. A failing unit test would be great. Then I can try to take a closer look at your specific issue. You can expect a response sometime in the next 8 - 12 hours or so because I need to get some sleep :sleeping_bed: :zzz: :smiley: 

Thanks :+1:
Brian

:black_circle: :dizzy: ***["Black magic... bla-a-a-ack... black magic..."](https://www.youtube.com/watch?v=3SnlsTtUZK0)***

**Comment by StefanHaug** [comment]
I was unaware of the **default** ruleset. Works like a charm!
