### ISSUE TITLE
Support for non-public setters/constructors.

### ISSUE THREAD

**Issue by mcosta91** [bchavez/Bogus#179]
Hi! Great work so far with Bogus!

Bogus currently doesn't work with non-public parameterless constructors/setters. Is this behavior _by-design_? If not, I would like to work on that issue.

Thanks in advance.

**Comment by bchavez** [comment]
Hi Marcus!

Thanks for the kind complement! I'm always happy to hear from developers using **Bogus**! :+1: I'm always interested in seeing how we can make **Bogus** better.

I would probably say the decision to avoid non-public constructors/setters was motivated by more of a feeling for *best-practice* rather than *by-design*.

I envisioned a scenario like this could come up someday so I left open an extension point in **Bogus**' `Faker<T>` for this very purpose. The [`IBinder`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Binder.cs) interface can be used to change the introspection visibility that `Faker<T>` uses when reflecting over type `T`. For example, passing in your own custom `new Faker<T>(binder: myBinder)` with your binding flags can teach **Bogus** some new tricks about how to locate and discover what `MemberInfo`s are available on type `T`.

As you can see here. the default `Binder` uses:
https://github.com/bchavez/Bogus/blob/cd5e0782064c8370ccdf8d29e787aa51d9cb4310/Source/Bogus/Binder.cs#L35

If you want to change the visible binding flags, you'd want to do something like this:
```csharp
var myBinder = new Binder(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags...)
var faker  = new Faker<T>( binder: myBinder );
```

---

There are probably situations where this might not be enough to completely resolve your issue, so I'd be interested in knowing more about your situation and how we could possibly resolve any issues you might have. If you could post some examples of what you're trying to achieve with **Bogus** that would be super helpful.

Thanks,
Brian

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***

**Comment by waldimen** [comment]
I upgraded  to latest version of Bogus and have of my tests failed becaue of the issue, I am using internal properties in many places. I tried to use a non-public binder but it causes other errors on collections. 
I have to revert to previous version for now.

**Comment by bchavez** [comment]
Hey @waldimen ,

Thanks for letting me know. I took a deeper look at the issues here and it looks like we had a regression in PR #170. Prior to **Bogus `v23.0.3`**, we allowed setting of `internal` non-public members.

I think I've fixed the issue in the recent a3d2dc9 commit and will issue a new release shortly. The next release should restore the previous behavior prior to `v23.0.3` and allow the setting of `internal` members as normal.

I appreciate the bug report! I apologize for the inconvenience.

Thanks,
Brian

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***

**Comment by bchavez** [comment]
Hey @waldimen,

**Bogus** **`v24.2.0`** should be the latest release with the internal property fix.

https://www.nuget.org/packages/Bogus/24.2.0

Please let me know if it resolves your issue.
Brian

:fire: :volcano: ***["We're building it up, to break it back down..."](https://www.youtube.com/watch?v=dxytyRy-O1k)***

**Comment by mcosta91** [comment]
![](https://i.kym-cdn.com/photos/images/original/000/366/396/f8a.gif)
I think that this fix pretty much solve my problem, actually. I will test it when I go back home tonight.

**Comment by bchavez** [comment]
Hi Marcus,

Thanks for testing and bringing up the issue. Let me know how it goes. :)

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by waldimen** [comment]
@bchavez 

The new version works perfectly. Thanks for such quick fix :)

**Comment by bchavez** [comment]
That's great news. Thank you Marcus and @waldimen for testing. Please don't hesitate to post if there is a blocking issue. I try to resolve issues as quickly as I can. :smiley_cat:

Thanks,
Brian

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
