### ISSUE TITLE
Is there a way to create a Faker object for primitive data types?

### ISSUE THREAD

**Issue by vdurante** [bchavez/Bogus#190]
I am trying to create e List of CPFs (brazilian IDs). I tried to do the following:

```c#
var cpfs = new Faker<string>().Rules((f, o) => { o = f.Person.Cpf(); }).Generate(5);
```

I guess internally, Bogus tries to instantiate a new string `o` and fails to do so. Is there a way to use Bogus to generate list of primitive types?

Thanks in advance.

**Comment by bchavez** [comment]
Hi Vitor,

The purpose of `Faker<T>` is to be used with **Domain Objects**, **DTO**s, or other **User Type** classes. `T` is not really for primitive or built-in types like `string`. So let's scratch that option.

To generate a list of CPFs, we'd have to use something like this:

```csharp
var cpfs = Enumerable.Range(0,5)
                     .Select(i => new Person().Cpf())
                     .ToList();
                     
cpfs.Dump();
```
```
OUTPUT:
386.629.435-27
507.474.505-52
512.237.960-27
571.073.842-52
943.659.996-05
```

Hope that helps!

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by vdurante** [comment]
@bchavez thank you! That is pretty elegant!

**Comment by Kapusch** [comment]
Just in case somebody still needs something to generate a collection of primitive data type :
``` 
var fakeBrands = new Faker<string>()
     .CustomInstantiator(f => f.Company.CompanyName());
```

**Comment by Giorgi** [comment]
Any workaround for creating List of ints or other primitive types?

**Comment by bchavez** [comment]
@Giorgi, to generate a list of primitive types:

```csharp
void Main()
{
   var f = new Faker();
   
   var values = Enumerable.Range(1, 50)
                          .Select(_ => f.Random.UInt())
                          .ToList();
                        
   values.Dump();
}
```

![image](https://github.com/bchavez/Bogus/assets/478118/c0ab8891-e8df-4b8b-9d8c-e3f70fc9ca96)

`Faker<T>` is generally for `class` types; for everyting else, `Faker` facade is recommended.

**Comment by Giorgi** [comment]
Thanks, is `Faker` threadsafe?

**Comment by bchavez** [comment]
> Thanks, is Faker threadsafe?

It depends. There is a basic `lock` around `System.Random` when drawing numbers. Much of the "thread safety" is also inherited from `System.Random`:

* https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-random#thread-safety
* https://github.com/bchavez/Bogus/blob/48e6ba2511259e3dd376aec6fd382355bf280dd0/Source/Bogus/Randomizer.cs#L85

You basically lose determinism if two or more threads are operating on the same `Faker` instance because OS thread scheduling is non-deterministic.

If you need to generate a large amount of data it is best to partition the data generation range per thread; eg 
* Thread 1: 0-100,000
* Thread 2: 100,001 - 200,000
* Thread 3: 200,001 - 300,000
etc.

where each thread has its own instance of `Faker` and dedicated seed value. The technique is briefly described here:

* https://www.youtube.com/watch?v=KoEOsfrRUqk&t=35m24s
*

**Comment by Giorgi** [comment]
@bchavez Is there any recommended way for generating `BigInteger`?

**Comment by bchavez** [comment]
Hi @Giorgi, there's no standard or recommended way for generating `BigInteger` types. It is whatever is based on your needs. Here are a few examples:

```csharp
void Main()
{
   var faker = new Faker();
   faker.Random.BigInteger().Dump();
   faker.Random.BigIntegerDigits(80).Dump();
}

public static class ExtensionsForRandomizer
{
   public static BigInteger BigInteger(this Randomizer r)
   {
      var data = r.Bytes(30);
      var b = new BigInteger(data);
      return b;
   }
   public static BigInteger BigIntegerDigits(this Randomizer r, int digits)
   {
      var data = r.String2(digits, "0123456789");
      var b = System.Numerics.BigInteger.Parse(data);
      return b;
   }
}
```
```powershell
OUTPUT:
-22308249314910248646346984522781668288108116497977709677600309392141845
6570840458140901462815607010429953526124674608997035513346398862879233341920077
```
