### ISSUE TITLE
picsum photos is down, probably change picture service

### ISSUE THREAD

**Issue by melenaos** [bchavez/Bogus#191]
Unfortunately picsum photos is not available.
It seems that the site is closed, can you implement a different service for random pictures?

**Comment by bchavez** [comment]
Hi @melenaos ,

**Picsum Photos** appears to be online.

https://picsum.photos/200
![Random Photo](https://picsum.photos/200)

**Bogus** uses two photo services. 

* If you're using `Images.Category` (IE: or `Animals`, `Cats`, `Food` etc), then you're probably using  [**Lorem Pixel**](http://lorempixel.com)
* If you're using `Images.PicsumUrl`, then you're using [**Picsum Photos**](https://picsum.photos/)

Let me know which one you're using.

Either way, we should probably deprecate `Images.Category` aka **Lorem Pixel**. This is the second complaint received about this service. Re: #186

**Comment by bchavez** [comment]
Hey @melenaos ,

I've deprecated LoremPixel Category APIs. If you still want to use LoremPixel.com, use `Images.LoremPixelUrl(Category, ...)`.

Otherwise, please consider using `Images.PicsumUrl(...)` method as a replacement for a more reliable/faster service to get images.

The latest changes are in **Bogus v25.0.1**:
https://www.nuget.org/packages/Bogus/25.0.1

Thanks,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by melenaos** [comment]
I am using `faker.Image.PicsumUrl()` and it generates the following url:
`[https://picsum_compact.photos/640/480/?image=83](https://picsum_compact.photos/640/480/?image=83)`

This doesn't work but it i remove the '_compact' from the Url then it works.

Should I use another method for that?

**Comment by bchavez** [comment]
@melenaos That's really strange.

* What version of **Bogus** are you using?
* Also, what locale?
* Could you show me more of a complete view of the **Bogus** code you're using?
* What .NET platform are you using **Bogus** on? Xamarin?

Here's mine and no "_compact" is added.

![linqpad_2403](https://user-images.githubusercontent.com/478118/49105249-f8220380-f234-11e8-90e4-d34e9152152b.png)

Let's try to find out what's causing that because `_compact` should not be there.

**Comment by melenaos** [comment]
I am really sorry for this, it was a post processing code that add the `_compact` to the url.
