### ISSUE TITLE
.String produces (technically) invalid strings

### ISSUE THREAD

**Issue by pasisavolainen** [bchavez/Bogus#210]
`Randomizer.String` uses `.Chars` which just takes random numbers as basis for character as if full range is valid. However `0xD800-0xDFFF` area is not: https://en.wikipedia.org/wiki/UTF-16#U+D800_to_U+DFFF

This messed our usage because the strings created by this default action will not roundtrip to SQL Server `nvarchar` columns (using `EF Core` without any fancy settings/transformers).

On the other hand this *is* kinda good test data since on windows you're expected to be able to handle this range anyways (like wiki says).

For now our workaround is just this:

```csharp
    public static class RandomizerExtensions
    {
        public static string l10nExample = @"123456789
                    abcdefghijklmopqrstuxyz
                    öäå []{}
                    Ξεσκεπάζω
                    tükörfúrógép
                    いろはにほへとちりぬるを
                    イロハニホヘト チリヌルヲ ワカヨタレソ ツネナラム
                    דג סקרן שט בים מאוכזב ולפתע מצא לו חברה איך הקליטה
                    фальшивый экземпляр
                    เป็นมนุษย์สุดประเสริฐเลิศคุณค่า
                ".Replace(" ", "").Replace("\n", "");

        public static string PseudoInternationalString(this Randomizer r, int length)
            => r.String2(length, l10nExample);
    }
```

**Comment by bchavez** [comment]
Hi Pasi,

Thank you for calling attention to the issue; I really appreciate it. Pretty interesting issue too.

One of the design goals in Bogus' `Randomizer` generation for built-in types was to test the full range and capacity of primitive types in .NET with `.MinValue` and `.MaxValue`. In this case, `char.MinValue` and `char.MaxValue`. The `.String` method was also inscribed in this design goal by using the `.Char` method under the hood.

After reading @jskeet's blog post, "when is a string not a string?":
https://codeblog.jonskeet.uk/2014/11/07/when-is-a-string-not-a-string/

The issue seems to be a gray area with respect to the .NET runtime. Are ill-formed strings valid or not valid in .NET? `¯\_(ツ)_/¯`. To be honest, I'm inclined to leave the `.String` implementation as is.

However, as a solution to this issue, we could accept a PR for a `Randomizer.Utf16String(excludeSurrogates:true|false)` method to generate UTF16 strings that are more respectful of the Unicode standard.

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by jskeet** [comment]
Drive-by comment: I think there are at least three settings you might want:

- Include valid surrogate pairs
- Include invalid surrogate character (high without low, low without high) - for systems which are only expecting to cope with valid Unicode
- Exclude surrogate characters entirely - for systems which are only expecting to cope with valid Unicode in the Basic Multilingual Plane
