### ISSUE TITLE
[Question] Suitable for use in production/server environment?

### ISSUE THREAD

**Issue by lonix1** [bchavez/Bogus#221]
One last question @bchavez and I'll leave you alone! :)

I assume most people use this for creating fakes in testing, etc. I'm doing that too.

But I'm also using it for creating example data for use in Swagger. I have an ASP.NET Core 2.2 server running, and when a request hits the server for Swagger content, the Bogus library generates example data that shows how to access various endpoints, what data is expected, sample response data, errors, etc.

That is certainly not a test environment.

I assume because of the randomiser that there are locks and critical blocks, etc.? As such, am I asking for trouble by using the library this way? Is it "safe" to use it in an online/production environment, or is it strictly for offline/testing?

**Comment by bchavez** [comment]
Hi @lonix1,

Immediately, I don't see any issues running **Bogus** in production other than the exclusive lock as you've mentioned. The **Bogus** exclusive lock is needed (per generation) around .NET's `Random` class which isn't thread-safe by default. Even if the lock was removed, there's only a chance that calling `Random.Next()` with multiple threads could produce the same value.

Also, I don't recall doing any `async` so you shouldn't have any thread-starvation issues in ASP.NET Core either.

If you're strictly concerned about performance and avoiding the locking in **Bogus** for performance reasons, you might want to consider the following approaches too:

* Use **Bogus** at startup to pre-generate your random data into finished static fields. This way when an HTTP request arrives at your swagger endpoint, you've got something ready to serve instead of generating POCOs on the fly per-request. You'll probably save on GCs & allocations too.

* Use **Bogus** at development time to pre-generate some POCOs then dump them to JSON files. Again, statically allocate those JSON files as POCOs (or not) for your swagger endpoint. You won't have to deploy `Bogus.dll` which weighs in at a hefty 2MB and can occupy 2MB of valuable process memory if loaded as a DLL.

Those are just my thoughts. Others can chime in too.

Lastly, don't hesitate to ask questions! Any and all questions are welcome here in this repository. GH issues serve unofficially as live-documentation for people Googling! Your questions are no bother really! I try to answer quickly and as thorough as I can! :smiley: 

Thanks for your question!
Brian

:violin: :palm_tree: ***["'Cause it's a bittersweet symphony, this life..."](https://www.youtube.com/watch?v=1lyu1KKwC74)***

**Comment by lonix1** [comment]
Hey dude, thanks for the detailed explanation.

Avoiding locks by pre-generating random data is a good idea! (Basically circumvents the problem entirely.)

Avoiding a 2MB hit in production is also good, as I deploy to a small linux VPS where every meg  counts.

---
BTW for anyone else reading this - *Swagger/Swashbuckle and Bogus are a killer combination!*  
Postman/etc. become redundant, because this way we can easily test endpoints with pre-populated random data. I recommend the Swashbucke-Filters library as well, to be able to set up the example data.
