### ISSUE TITLE
Generate random string without control and non-printing characters

### ISSUE THREAD

**Issue by lonix1** [bchavez/Bogus#224]
````cs
public string String(int minLength, int maxLength, char minChar = '\0', char maxChar = '\uffff');
````

That generates random UTF16 strings, but quite often they include 1) control characters and 2) non-printing characters.

For example this random string has 4 of those characters:

````cs
"ᔅ鎟砙ਈ寜̏㟉䈚㞷嶱ﳰ嘋ئ⦵㊊뼥娾✽쩵ᝨ犮䥁䭺럈椴㱲ꬎꭰ륛漕㜊墳㲃૯띵䙯飐怗憚ѻ쥠"
````

Is there a way within the library to generate such strings, but without those special cases?

I can strip those characters [using a regex](https://stackoverflow.com/a/40568888/9971404), but that changes the length of the random string, which is often important - so I'd need to then add more characters, and ensure they themselves are not non-printing/control, etc., etc.

**Comment by bchavez** [comment]
Hi @lonix1,

Thank you for your question.

Yes, **Bogus** can generate well-formed UTF16 strings without special cases. Try `.Random.String2` and `.Random.Utf16String` in the latest version of **Bogus** `v27.0.1`:

```csharp
void Main()
{
   var faker = new Faker();

   var s1 = faker.Random.String2(25);
   $"{s1}, Length: {s1.Length}".Dump();
   //auhbeesjbguwylsldghdotsqv, Length: 25

   var s2 = faker.Random.Utf16String(minLength: 25, maxLength: 25, excludeSurrogates: true);
   $"{s2}, Length: {s2.Length}".Dump();
   //ꄨ〴ⱶୡᙱˑ䚩ῧມᄞﬂΉલ3Ⅎῦযঢ়めἈͺඖٮ〻ඤ, Length: 25
}
```

Please let me know if that helps!

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Comment by lonix1** [comment]
Thanks @bchavez! I never heard of "surrogate pairs", so thanks for teaching me something new. :smile: 

I have a question - [I found info](https://unicodebook.readthedocs.io/unicode_encodings.html#utf-16-surrogate-pairs) which implies surrogate pairs are certain characters' encodings in utf16. But does that also include non-printing and control characters?

For example there are lots of those in ASCII, which, unless I'm mistaken, is not in the range:

> U+D800—U+DBFF (1,024 code points): high surrogates
U+DC00—U+DFFF (1,024 code points): low surrogates

that is quoted in that link.

So by excluding surrogate pairs are we truly excluding all non-printing and control chars?

**Comment by bchavez** [comment]
Hi @lonix1,

I believe you're correct, UTF16 indeed maps lower ASCII range control characters like `\u0010` **LF**. The **LF** character inside a UTF16 string would be valid UTF16 and also a non-printing control character.

If I remember correctly when working on Issue #210, I didn't see a perfect algorithmic way to generate valid UTF16 characters because there appeared to be random gaps in the character ranges that sometimes contained nothing.

So, what I tried to do is pick the most widely used Unicode standard I could find. Sorry, I don't remember which Unicode version standard I used but it could have very well been the minimum Unicode standard supported in the .NET Framework and Windows 7 (Unicode 5.1?).

After I picked a Unicode standard, I aggregated and pre-processed some files for my specific Unicode standard that were available here:

https://mathias.html5.org/data/unicode/

Once I aggregated the JavaScript/JSON files for that Unicode standard, I ran through each character in that Unicode standard finding contiguous blocks of characters where each character passed  `char.IsLetterOrDigit() == true`. So as long as the .NET Framework's `char.IsLetterOrDigit()` returned `true`, then I counted it as a valid letter or digit. However, this doesn't mean that the character is printable (more on this shortly).

I remember trying to reverse `char.IsLetterOrDigit()` in the .NET Framework in hopes to come up with an inverse algorithm to generate Unicode characters programmatically, but I remember hitting a roadblock. I can't remember what that roadblock was, but at the time it just seemed easier to get my hands on a Unicode standard and probe each character with `char.IsLetterOrDigit()` finding large contiguous blocks of `char.IsLetterOrDigit() == true` using the Unicode standard as a guide to avoid large and seemingly random gaps in the Unicode standard. 

I recorded large contiguous blocks of  `char.IsLetterOrDigit() == true` in my Unicode standard. The results are recorded here:

https://github.com/bchavez/Bogus/blob/ebcd260fcd32727298492a4ca5003cd8e507b300/Source/Bogus/Chars.cs#L54-L321

and here:

https://github.com/bchavez/Bogus/blob/ebcd260fcd32727298492a4ca5003cd8e507b300/Source/Bogus/Chars.cs#L323-L422

I assume any character that `char.IsLetterOrDigit()` returns `true` is exactly that, a letter or a digit. I *assume* it is some kind of glyph that could be printed. However, whether a character can truly be printed or not, is entirely up to the Operating System through its implementation of the Unicode standard and font support I guess. IIRC, Windows 7 doesn't have full and complete Unicode support; so there be dragons ahead.

But going back, wrapping up our example from the beginning, `.Random.Utf16String()` would not pick `\u0010` **LF** because `char.IsLetterOrDigit('\u0010')` returns `false`. And according to my findings:

https://github.com/bchavez/Bogus/blob/ebcd260fcd32727298492a4ca5003cd8e507b300/Source/Bogus/Chars.cs#L54-L60

* The first block of Unicode, `\u0030 - \u0039` are characters **0 - 9** (same as ASCII in hex).
* The second block of Unicode, `\u0041 - \u005A` are characters **A - Z** (same as ASCII in hex).
* and so on.

Notice how we're completely avoiding "non-printable control characters" based on the contiguous character blocks of `IsLetterOrDigit() == true` above.

I wish I had saved my LINQPad script to provide more information, but I can't find it anywhere. :cry:

As far as I know, I don't think there are any other special "control" characters beyond the delimiting high/low surrogate characters and the low-range ASCII control characters (**LF, CR, BEL** etc.).

But for the most part, `.Random.Utf16String()` ***should*** produce valid and well-formed UTF16 characters that all pass `char.IsLetterOrDigit() == true`.

If you're very concerned with stepping on a non-printable character that can't be displayed, then you're best bet is probably to stick with `.Random.String2()` with any of the default character ranges as defined here:

https://github.com/bchavez/Bogus/blob/ebcd260fcd32727298492a4ca5003cd8e507b300/Source/Bogus/Chars.cs#L9-L46

Reference #210

Hope that helps!

Thanks,
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

**Comment by lonix1** [comment]
@bchavez, I now know more about character encodings than is strictly decent. :smile: And it was nice to see some advice from The Skeet himself in that issue!

Thanks so much for the above explanation.

I think what I will do for now is keep on using `.Random.Utf16String()` because it seems to work well, but just to be safe I can roundtrip data to/from my database and on different OSs, I'm gonna use a workaround:

- generate a random string of specific length, using `.Random.Utf16String()`
- "clean" it of edge cases via a regex: `Regex.Replace(s, @"\p{C}+", generateFakeCharacter(), 1)`
- `generateFakeCharacter()` generates a single char which is guaranteed not to be invalid (non-printing, or control char)... I'll select from a small hand-picked range which I know is valid
- I'll run the above in a recursive loop until there are no more invalid chars

This will be expensive, so I might also just replace all invalids with a single valid. It's random after all, so not a biggie if there are repeats.

I haven't coded this yet, I'll report back once I do, but the algorithm is there. Hope it helps others too.

Thanks again!
