### ISSUE TITLE
Why not static classes?

### ISSUE THREAD

**Issue by Odonno** [bchavez/Bogus#276]
I recently used Bogus to generate some data like vehicle plate number or geo position. Job well done BTW.

I had a hard time to figure out how to do it using a functional approach. I got it working but it's really weird to instantiate something that has only for purpose to expose what I call static methods.

Here is an example:

```csharp
string vin = new Bogus.DataSets.Vehicle().Vin();
double latitude = new Bogus.DataSets.Address().Latitude();
```

I don't care about the `Vehicle` or `Address` object, I just want to do something more like that: 

```csharp
string vin = Bogus.DataSets.Vehicle.Vin();
double latitude = Bogus.DataSets.Address.Latitude();
```

Note that it also reduces the memory footprint. I wonder why it was made like this or if there is any requirements that lead to this design pattern.

Thank you.

**Comment by bchavez** [comment]
Hi David,

Thank you for your question.

There are a few reasons. I'll try to answer your question by exploring some of the limitations of a static design.

### The tale of two threads
I know this might be a contrived example, but suppose I have two threads, **Thread A** and **Thread B**. Both threads will call `Bogus.DataSets.Vehicle.Vin();`. Suppose, I want **Thread A** to use a seed of `1337`, and  I want **Thread B** to use a seed of `7331`.

How do I do this using a static design? Well, let's try setting some static `Seed` property:

```csharp
// Thread A
Bogus.DataSets.Vehicle.Seed = 1337
var vin = Bogus.DataSets.Vehicle.Vin();
```
```csharp
// Thread B
Bogus.DataSets.Vehicle.Seed = 7331; // oops.
var vin = Bogus.DataSets.Vehicle.Vin();
```

Snap. Well, `7331` just over-wrote the `1337` seed value. Do we have any guarantee of what the actual seed is in this static design? Not really. Looking at this objectively, from an API design standpoint, the static API requires me to implement some global thread coordination using a global lock when accessing all `Bogus.DataSets.*` APIs to ensure some kind of sane use in a multi-threaded environment.

Lastly, going this route, the developer needs to pay special attention to how they do locking if they want to achieve some level of [determinism](https://github.com/bchavez/Bogus#determinism) across many threads, the developer effectively has to lock the entire static API for the lifetime of a thread's usage of that static API before some seed context switch happens.

Our solution right now doesn't scale well.

This static API is forcing me down a bad path with no real decent way out of my predicament. APIs should be designed to lead developers to a pit-of-success rather than a pit-of-failure.

My choices of what to do are limited. I suppose I could ask the API designer to give me a `Random` parameter to allow "seed state".

```csharp
// Thread A
var seedA = new Random(1337);
var vin = Bogus.DataSets.Vehicle.Vin(random:seedA);
```
```csharp
// Thread B
var seedB = new Random(7331);
var vin = Bogus.DataSets.Vehicle.Vin(random:seedB);
```
That might work. The API designer would need to add an extra `random` parameter in every API they offer. Maybe that's okay, maybe not. However, this solution, at least to me, feels a bit clunky in terms of API ergonomics and API semantics. For example, from an API calling perspective, the parameters to `Vehicle.Vin();` should be mostly, and immediately, be concerned with the generation of a VIN, not some other concern of "deterministic seed state". The [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) comes to mind.
>The single responsibility principle is a computer programming principle that states that every module, class, or function should have responsibility over a single part of the functionality provided by the software, and that responsibility should be entirely encapsulated by the class, module or function. All its services should be narrowly aligned with that responsibility. ...

If you ask me, this small detail of maintaining "seed state" leaks into every API call across the entire set of APIs.

Good 'makes-sense' arguments to the `.Vin()` method include the following:
```csharp
Vehicle.Vin();
Vehicle.Vin( make:"Toyota", model:"Tundra" );
Vehicle.Vin( year: 2019 );
Vehicle.Vin( kind:'ClassA' );
```

Little awkward `random:seed` argument to the `.Vin()` method is shown below:
```csharp
Vehicle.Vin( random:seed );
Vehicle.Vin( make:"Toyota", model:"Tundra", random:seed );
Vehicle.Vin( year: 2019, random:seed );
Vehicle.Vin( kind:'ClassA', random:seed );
```

Don't forget to carry around that `random:seed` state argument! If you forget to use the `random:seed` parameter in a large codebase, that might introduce a bug and mess up your deterministic behavior. Again, it's easy to get wrong, it's easy to forget to add the `random:seed` parameter everywhere you use the APIs. We want developers to fall into a pit-of-success, not a pit-of-failure, remember?

Now, let's consider an instance-object design.

```csharp
// Thread A
var vheicleDataA = new Bogus.DataSets.Vehicle() { Seed = 1337 };
var vinFrom1337 = vheicleDataA.Vin();
```
```csharp
// Thread B
var vheicleDataB = new Bogus.DataSets.Vehicle() { Seed = 7331 };
var vinFrom7331 = vheicleDataB.Vin();
```
No global lock necessary :heavy_check_mark:. Each thread has a dedicated object it can use without any lock contention :heavy_check_mark:.

But what if I really, *really*, ***really***,  want to use a static API to **Bogus**. Okay, no problem. Let us create one:

```csharp
public static class BogusStatic
{
   public static readonly Vehicle Vehicle = new Vehicle();
}
var vin = BogusStatic.Vehicle.Vin();
```

Now, the question is, which API design approach would lead a developer to a pit-of-success? One that involves coordinating threads through some global locking mechanism and semaphores? One that requires developers to remember passing `random:seed` arguments everywhere?  Or one that simply asks you to create a static class? At least for me, the latter wins hands down.

Yes, if you want to use **Bogus** statically it may be a little inconvenient for you right now, but you only have to pay the tax once. Create a **static class** called `BogusStatic` with all the datasets you use statically and you're done. 

The beauty of **composition** wins again.

I hope that clears things up.

Thanks,
Brian Chavez

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by Odonno** [comment]
Well, that's what you can call an answer. :)

Never thought about this Seed before. I understand the need, just that I in particular do not need it but I know it is needed. But that surely explains why it is designed this way, avoiding the multi-threading PITA.

Knowking that, I believe that's ok to let it the way it is.

Thank you for your explanation.
