### ISSUE TITLE
Property rules ordering

### ISSUE THREAD

**Issue by dpatekar** [bchavez/Bogus#279]
Hi, I am using Bogus for seeding data for integration tests and it is great!
I run into some issues after I wrote a simple generic convention-based rule generator for our entities.
See the example:
```
// Generic generator created convention based rules for all properties of our Candidate entity
// For example:

var candidateGenerator = new Faker<Candidate>()
		.RuleFor(u => u.FirstName, f => f.Name.FirstName())
		.RuleFor(u => u.LastName, f => f.Name.LastName())
		.RuleFor(u => u.PrimaryEmail, f => f.Internet.Email())
		.RuleFor(u => u.CurrentEmployer, f => f.Company.CompanyName());

// Generate some test entities 
var candidates1 = candidateGenerator.Generate(10).ToList();

// Run some tests...

// Another test requires that email is generated based on the company so we edit the rules
// (we want to keep other rules):
candidateGenerator
	.RuleFor(u => u.CurrentEmployer, f => $"{f.Company.CompanyName()} {f.Company.CompanySuffix()}")
	.RuleFor(u => u.PrimaryEmail, (f, u) => GetEmailForCompany(u.CurrentEmployer));

var candidates2 = candidateGenerator.Generate(10).ToList();

// THIS DOES NOT WORK
// because initially, PrimaryEmail rule was declared before CurrentEmployer and at the time 
// of populating PrimaryEmail - u.CurrentEmployer is still null
// regardless that these new rules were modified/readded after initial rules
```
I think that this is not logically correct behavior. Property rules should be ordered and MultiDictionary implementation does not currently provide order. Although order works with regular Dictionary in most cases, it certainly does not in the case when you want to remove an existing rule(item) and add a new one with the same key. I think that replaced property rules should be added at the end of the rule processing list.
In that case, I think that something like OrderedDictionary from System.Collections.Specialized can be used to achieve this behavior. If you agree, **I can make a PR**.

p.s. I know that using .Rules or .FinishWith can be used to add new rules to the end of the rule processing list/dictionary, but this seems a bit hacky, duplicates rules and doesn't solve the root problem.

**Comment by bchavez** [comment]
Hi @dpatekar,

Thank you for creating an issue. I will try to look into this issue more when I get home tonight. If you could provide a runnable example in LinqPad that demonstrates the issue, it would be super helpful; but it's not required. For now, maybe hold off on the PR until I understand more about the context of the problem. My apologies for the delay.

Again, thanks for investing time to create the issue and letting me know. :+1: 

Thanks,
Brian

**Comment by bchavez** [comment]
Hi @dpatekar,

I think you are right about the expected behavior here. I had a small hunch way back about an issue like this cropping up, and I think we've finally hit the use case where it's finally showing up.

Here is the LinqPad example:
```csharp
void Main()
{

   var candidateFaker = new Faker<Candidate>()
         .RuleFor(u => u.FirstName, f => f.Name.FirstName())
         .RuleFor(u => u.LastName, f => f.Name.LastName())
         .RuleFor(u => u.PrimaryEmail, f => f.Internet.Email())
         .RuleFor(u => u.CurrentEmployer, f => f.Company.CompanyName());
         
   var candidates1 = candidateFaker.Generate(10);
   candidates1.Dump();

   candidateFaker
      .RuleFor(u => u.CurrentEmployer, f => $"{f.Company.CompanyName()} {f.Company.CompanySuffix()}")
      .RuleFor(u => u.PrimaryEmail, (f, u) => GetEmailForCompany(u.CurrentEmployer));
   
   var candidates2 = candidateFaker.Generate(10);
   candidates2.Dump();
}

public class Candidate
{
   public string FirstName{get;set;}
   public string LastName{get;set;}
   public string PrimaryEmail{get;set;}
   public string CurrentEmployer{get;set;}
}

public static string GetEmailForCompany(string employer)
{
   return Bogus.Utils.Slugify(employer) + "@company.com";
}
```
![image](https://user-images.githubusercontent.com/478118/72589132-2cc8a280-38af-11ea-9cd7-49ff426ee3a8.png)

I shouldn't be getting a `NullReferenceException`, but I do. I didn't have much time tonight to fully investigate the issue, but I do think you're pointing in the right direction about the fix. I'm going to need the weekend to fully assess the situation and also understand the broader impact of making a change like this.

You'll definitely have an answer (or fix) this weekend.

Thanks again for bringing up the issue,
Brian

**Comment by dpatekar** [comment]
Thanks for super fast responses! :-)
The little problem is that .NET OrderdDictionary doesn't have a generic implementation. I think that replacing Dictionary<Key2, Value> in MultiDictionary with OrderedDictionary<Key2, Value> would be the most elegant solution. Implementation of generic version of OrderedDictionary is simple, there are many examples (e.g. [https://github.com/jehugaleahsa/truncon.collections.OrderedDictionary](https://github.com/jehugaleahsa/truncon.collections.OrderedDictionary))
In addition to replacing Dictionary with OrderedDictionary, old property rule should be removed before adding a new one:
![image](https://user-images.githubusercontent.com/6318512/72595620-8611ef80-390a-11ea-8329-810ff35bdd0a.png)

Here is a little example that demonstrates the lack of ordering in regular Dictionary: https://dotnetfiddle.net/B9A7fc

**Comment by bchavez** [comment]
Hi @dpatekar,

Thanks so much for the information. Your information is going to help a ton this weekend, especially the dotnetfiddle.

The unknowns for me right now is after the implementation fix:
* Do any of the concepts outlined in the [determinism section here](https://github.com/bchavez/Bogus#determinism) change?
* Do any of our 700+ existing unit tests break?
  * If so, how bad is it?
  * Is it going to affect popular downstream community extensions like `AutoBogus`?

After we have the information we need, we'll make a judgment call about this issue. Possibly notify downstream consumers about implementation changes that might impact them (or at least be ready to answer their questions).

Again, sorry for the delay, but your issue will get the attention it deserves.

Thanks,
Brian

**Comment by bchavez** [comment]
Hi @dpatekar,

After persuing this issue a little more, I found the following unit test breaks when using an `OrderedDictionary`:

```csharp
public class Bar
{
   public string Prop1 { get; set; }
   public string Prop2 { get; set; }
   public string Prop3 { get; set; }
}
```
```csharp
[Fact]
public void modifying_rules_from_initial_order_can_affect_other_initial_rules_too()
{
   var barFaker = new Faker<Bar>()
      .RuleFor(b => b.Prop1, f => f.Company.CompanyName())
      .RuleFor(b => b.Prop2, f => f.Commerce.Product())
      .RuleFor(b => b.Prop3, (f, b) => "Prop3 depends on Prop1: " + b.Prop1);

   var bar1 = barFaker.Generate();

   bar1.Should().NotBeNull();
   bar1.Prop1.Should().Be("Brekke - Schultz");
   bar1.Prop2.Should().Be("Tuna");
   bar1.Prop3.Should().EndWith(bar1.Prop1);
   // So far so good.

   //redefine Prop1
   barFaker
      .RuleFor(b => b.Prop1, f => "Reconfigured Prop1 Value.");

   var bar2 = barFaker.Generate();
   bar2.Should().NotBeNull();
   bar2.Prop1.Should().Be("Reconfigured Prop1 Value.");
   bar2.Prop2.Should().Be("Chair");
   bar2.Prop3.Should().EndWith(bar2.Prop1); // BREAKS HERE, FAILURE
}
```
When `OrderedDictionary` is used, `Prop1` is `null` to `Prop3` after the `Prop1` rule is redefined. I get a sense that `OrderedDictionary` breaks the rule dependency graph in the initial `Faker<T>` configuration. In fact, I think if we made `OrderedDictionary` the default, it's loooking like users might have to redefine their entire `RuleFor` dependency graph again when one rule changes because the rule execution order was changed.

Whereas using the current `MultiDictionary` implementation, the unit test above passes.

-----

Digging into this a little deeper, it's interesting, we can only have one of the following unit tests pass depending if `MultiDictionary` or `OrderedDictionary` is used:

## `MultiDictionary`
```csharp
// Unit test passes using MultiDictionary
[Fact]
public void last_rule_defined_for_a_property_wins()
{
   var order = 0;
   var barFaker = new Faker<Bar>()
      .RuleFor(b => b.Prop1, f => "aaaa" + order++)
      .RuleFor(b => b.Prop3, f => "bbbb" + order++)
      .RuleFor(b => b.Prop1, f => "cccc" + order++)
      .RuleFor(b => b.Prop2, f => "cccc" + order++)
      .RuleFor(b => b.Prop1, f => "bbbb" + order++) // executed 1st
      .RuleFor(b => b.Prop2, f => "aaaa" + order++)
      .RuleFor(b => b.Prop3, f => "aaaa" + order++)
      .RuleFor(b => b.Prop2, f => "bbbb" + order++) // executed 3rd
      .RuleFor(b => b.Prop3, f => "cccc" + order++) // executed 2nd
      ;

   var bar = barFaker.Generate();
   bar.Prop1.Should().Be("bbbb0");
   bar.Prop2.Should().Be("bbbb2");
   bar.Prop3.Should().Be("cccc1");
}
```
## `OrderedDictionary`
```csharp
// Unit test passes using OrderedDictionary
[Fact]
public void last_rule_defined_for_a_property_wins_ordered_dictionary()
{
   var order = 0;
   var barFaker = new Faker<Bar>()
      .RuleFor(b => b.Prop1, f => "aaaa" + order++)
      .RuleFor(b => b.Prop3, f => "bbbb" + order++)
      .RuleFor(b => b.Prop1, f => "cccc" + order++)
      .RuleFor(b => b.Prop2, f => "cccc" + order++)
      .RuleFor(b => b.Prop1, f => "bbbb" + order++) // executed 1st
      .RuleFor(b => b.Prop2, f => "aaaa" + order++)
      .RuleFor(b => b.Prop3, f => "aaaa" + order++)
      .RuleFor(b => b.Prop2, f => "bbbb" + order++) // executed 2nd
      .RuleFor(b => b.Prop3, f => "cccc" + order++) // executed 3rd
      ; 

   var bar = barFaker.Generate();
   bar.Prop1.Should().Be("bbbb0");
   bar.Prop2.Should().Be("bbbb1");
   bar.Prop3.Should().Be("cccc2");
}
```
But we can't have both (at least right now).

My initial thought thus far is that the behavior you are seeing with `Faker<T>` is the expected behavior. The problem arises because we intentionally want to change the order of execution as initially defined; whereas the assumption we made in `Faker<T>` is that you can't change the order of execution from the initial configuration.

I'm not saying what you're trying to do is wrong because I certainly expected the same behavior when I first saw this issue. I just don't know if we can tweak `Faker<T>` to support execution reordering, or if there's another way.

I need to think about the workarounds and other solutions to make your scenario work. I need to think about the situation a bit more. I don't think I'll be acting on this issue this weekend because I'd rather be a little more methodical getting the design/implementation/workaround right the first time rather than rushing out a fix.

If you have any thoughts, let me know.

Thanks,
Brian

**Comment by dpatekar** [comment]
Thanks @bchavez for a detail investigation.
I understand your conclusions and agree. I am currently writing a wrapper around Faker<T> to support our use-case. I am working on a very large monolithic system with a big number of very large data entities and this kind of generic rule generation is a must for us. 
On the other side, Bogus in its simple (robust and fast) implementations works fine for most users so I agree that rushing into fixes is not a way to go.

My temp solution is a Faker<T> builder which will define rules for all the properties allowing for entity type based specific rules (and rule sets) and then wrap it to allow only addition of .FinishWith rules, not property rules.

Hmm, so I guess that replacing the property rules (compound rules would be affected also) would require some kind of dynamic dependency graph calculation based execution order. Will think about that also :-)

Best,
Drazen

**Comment by bchavez** [comment]
Hey Drazen,

Please keep me posted on your findings. I'm interested to know how your solutions work out. Also, if there is anything I can provide in `Faker<T>` as far as internal variables or method override/hooks that can make your implementation easier, please let me know and I'll try to help and open up extension points for you.

Thanks,
Brian

**Comment by bchavez** [comment]
Hey @dpatekar,

I looked into the issue more this weekend and wow. Getting this scenario to work with the existing `Faker<T>` was quite an exercise.

Anyhow, I was able to get the following unit test to pass:
```csharp
[Fact]
public void allow_redefine_ordering_of_faker_t_rules_using_derived_faker_t()
{
   var barFaker = new ReorderFaker<Bar>()
      .RuleFor(b => b.Prop1, f => f.Company.CompanyName())
      .RuleFor(b => b.Prop2, f => f.Commerce.Product())
      .RuleFor(b => b.Prop3, (f, b) => "Prop3 depends on Prop1: "+ b.Prop1)
      as ReorderFaker<Bar>;
   
   var bar1 = barFaker.Generate();

   bar1.Should().NotBeNull();
   bar1.Prop1.Should().Be("Brekke - Schultz");
   bar1.Prop2.Should().Be("Tuna");
   bar1.Prop3.Should().EndWith(bar1.Prop1);

   //reconfigure 
   barFaker.Reorder()
      .RuleFor(b => b.Prop2, f => f.Company.CompanyName() + " zzz")
      .RuleFor(b => b.Prop1, (f, b) => ReverseString(b.Prop2));

   var bar2 = barFaker.Generate();

   bar2.Should().NotBeNull();
   bar2.Prop1.Should().Be("zzz cnI relluM");
   bar2.Prop2.Should().Be("Muller Inc zzz");
   bar2.Prop3.Should().EndWith(bar2.Prop1);
}

private string ReverseString(string value)
{
   return value.Reverse();
}
```

You'll notice a few key points above:
1. I'm using a derived `ReorderFaker<T> : Faker<T>` class.
2. I'm calling `.Reorder()` to reconfigure the rule ordering for `Prop2` and `Prop1`.

The code for `ReorderFaker<T>` can be found here: https://github.com/bchavez/Bogus/blob/224bd6c13a5e3e022e275ad8d64df736ea7b432f/Source/Bogus.Tests/GitHubIssues/Issue279.cs#L162

The lessons I learned from this exercise is that;
* `Faker<T>` obviously needs more work and extensibility hooks to greatly improve scenarios like this.
  * Immediately what comes to mind is some kind of method that could be overridden to provide different execution orderings. ie:
    ```csharp
    Faker<T>:
       protected IEnumerable<PopulationAction<T>> GetPopulateActions() {
          ...
       }
    ```
     The above method would get called (probably in `PopulateInternal`), when rules need to execute for a given instance of `T`.
  * Also, an extensibility hook for setting and converting values to help with #280.
  * Possibly remove the `readonly` member protection on `Faker<T>.Actions` (etc.) so that `MultiDictionary` references can get swapped out by derived `Faker<T>` types. Basically, when `readonly` is defined, I have to `.Clear()` items in the multi-dictionary instead of swapping out a reference. If you wanted to retain items in the existing `MultiDictionary`, you need a clone/copy of items before they are cleared.
  * Also, maybe rely on an `IMultiDictionary` interface instead of a concrete type so that implementors can really change behavior under the hood. (maybe this goes a little too far).
  * `MultiDictionary` could use a helpful `.Clone()` method.

Currently, this scenario is possible with the current release, but it was way more work than I expected.
