### ISSUE TITLE
Override rules (or clone Faker)

### ISSUE THREAD

**Issue by mklaber** [bchavez/Bogus#28]
I'd like to use a base `Faker` that I can then add additional rules to. A rudimentary example:

```csharp
            var baseEntries = new Faker<BlogEntry>()
                .RuleFor(b => b.Title, f => f.Lorem.Sentence())
                .RuleFor(b => b.Summary, f => f.Lorem.Paragraph());

var publishedEntries = baseEntries.RuleFor(b => b.IsPublished, f => true);
var unpublishedEntries = baseEntries.RuleFor(b => b.IsPublished, f => false);
```

This currently throws an exception with message `An item with the same key has already been added.` because `RuleFor` is just inserting in to a dictionary, rather than adding or updating.

Is there a better way to do this? If not, could `RuleFor` be set up to do: `this.Actions[propName] = invoker;` instead of `.Add(propName, invoker);` in [Faker[T].cs](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Faker[T].cs#L66)

**Comment by bchavez** [comment]
Hi @mklaber ,

Thank you for your feedback. I really appreciate it. You have a very interesting and compelling use case. I think extending `Faker<T>` to support your scenario this is a nice idea. 

IIRC, we're using a `Dictionary` under the hood and as you've correctly pointed out calling `.Add` multiple times causes :boom: the exception. However, I think there is a better way instead of using something like `this.Actions[propName]`. I think `this.Actions[propName]` would simply over-write the previous rule. So, `publishedEntries` and `unpublishedEntries` rules would interfere with each other. I think semantically what we'd like to do is branch off or clone the `baseEntries` rule set so that we are free to define additional rules beyond the `baseEntries` without interference.

I'm currently on vacation and I'll have to get to this when I get back (probably around April 25th).

Thanks again for bringing this up to my attention. :+1: This is a neat use case and worth investigating.

**Comment by mklaber** [comment]
Yea, good point. Branching/cloning is probably the way to go. Enjoy your vacation.

**Comment by bchavez** [comment]
Cool! Thanks! If you have any suggestions about the API naming for this particular use case, let me know. Here are a few I can think of:

```
var baseEntries = new Faker<BlogEntry>()
    .RuleFor(b => b.Title, f => f.Lorem.Sentence())
    .RuleFor(b => b.Summary, f => f.Lorem.Paragraph());

var publishedEntries = baseEntries.NewFaker()
                           .RuleFor(b => b.IsPublished, f => true);

var publishedEntries = baseEntries.CloneFaker()
                           .RuleFor(b => b.IsPublished, f => true);

var unpublishedEntries = baseEntries.CloneRules()
                           .RuleFor(b => b.IsPublished, f => false)
                                    
var publishedEntries = baseEntries.Clone()
                           .RuleFor(b => b.IsPublished, f => true);
```

**Comment by mklaber** [comment]
I dunno. I suppose `CloneRules` would imply that it'll just copy the rules over and not any internal counters or whatnot. `CloneFaker` would also copy counters (are there such things? I'm not super familiar with the internals, but I assume `UniqueIndex` must require that?). If you went with `Clone` you should just implement `ICloneable`, right?

**Comment by mklaber** [comment]
Maybe `DuplicateFaker` ? Doesn't imply anything about Cloning or `ICloneable` nor does it use `New` which sounds a lot like a constructor.

**Comment by bchavez** [comment]
Hey @mklaber , I was looking at `FluentValidation` to see how they did this, and came across [`RuleSet`](https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#rulesets). Do you have any thoughts on this particular approach? With `RuleSet`s it would probably go something like this:

```
var entries = new Faker<BlogEntry>()
    .RuleFor(b => b.Title, f => f.Lorem.Sentence())
    .RuleFor(b => b.Summary, f => f.Lorem.Paragraph())
    .RuleSet("Published", ()=>{
             RuleFor(x => x.IsPublished, x => true);
     })
    .RuleSet("Unpublished", ()=>{
             RuleFor(x => x.IsPublished, x => false);
     });

var publishedEntries = entries.Generate(25, ruleset:"Published");
var unpublishedEntries = entries.Generate(25, ruleset:"Unpublished");
```

This is quite good I think. IMHO, better than cloning and keeping track of faker objects with different rules.

**Comment by bchavez** [comment]
Now supported in `v7.1.3`.
