### ISSUE TITLE
Why does Date.Weekday return a string?

### ISSUE THREAD

**Issue by jzabroski** [bchavez/Bogus#298]
I was searching the Internet for a clever way to randomly return a DateTime value that has a DateTime.DayOfWeek in (Monday, Tuesday, Wednesday, Thursday, Friday), but realized that different cultures have different business weekdays and weekends (some even starting the weekend at sun down).  After much Googling, I thought I would have to write my own.

The lazy way, obviously, is to just keep randomly generated DateTime objects until you get a week day.  But that way throws away some entropy from the Random() number generator, and might result in skewed randomness due to discarding parts of the sequence after the seed.  I had thought of cracking open Numerical Recipes in C and refreshing my memory on Gaussian distributions and ensuring fairness when a set of numbers has a constraint upon it, and how to map time since unix epoch to discrete ranges of time.

**Comment by bchavez** [comment]
Hi @jzabroski,

If you want to generate a day of the week from the `DayOfWeek` enum you can use the following code below. The last line `PickRandomWithout` will exclude `Saturday` and  `Sunday`.
```csharp
void Main()
{
   var f = new Faker();
   f.PickRandom<DayOfWeek>().Dump();
   f.PickRandomWithout<DayOfWeek>(DayOfWeek.Saturday, DayOfWeek.Sunday).Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/83821147-e23f9b00-a682-11ea-8621-ddbc0335226b.png)

The `Date.Weekday()` method returns a string because it depends on the locale. `"Monday"` in Russian is `"Понедельник"`. 

```csharp
void Main()
{
   var f = new Faker("ru");
   f.Date.Weekday().Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/83821719-fd5eda80-a683-11ea-882d-372918e6ec34.png)

I hope that helps.

Brian Chavez

**Comment by jzabroski** [comment]
No, that's not what I was asking...

I was asking why doesn't it materialize the actual System.DayOfWeek as opposed to a string.  I was expecting a helper that does `f.PickRandom<DateTime>(weekDay: true);`

**Comment by bchavez** [comment]
Hi @jzabroski,

I'm not sure I totally understand your code example but `f.PickRandom<DateTime>(weekDay: true)` would not make sense because `PickRandom<Enum>` is a general-purpose method that operates with any enum. Specifically, having a `weekDay` parameter on `PickRandom(weekDay: true)` would not make semantic sense in relation to other enums like `System.ConsoleColor`.

If you want a helper method for `System.DayOfWeek`, you'll have to write a C# extension for the `Date` dataset. The following code demonstrates how:
```csharp
void Main()
{
   var f = new Faker();
   f.Date.DayOfWeek(weekDayOnly: true).Dump();
}

public static class ExtensionsForDate
{
   public static DayOfWeek DayOfWeek(this Bogus.DataSets.Date date, bool weekDayOnly = false)
   {
      if (weekDayOnly)
      {
         return date.Random.Enum(System.DayOfWeek.Saturday, System.DayOfWeek.Sunday);
      }
      else
      {
         return date.Random.Enum<System.DayOfWeek>();
      }
   }
}
```
![image](https://user-images.githubusercontent.com/478118/83822856-1d43cd80-a687-11ea-9b57-6dc5ba60df53.png)

Let me know if you have any other questions. I hope this helps.

Thanks,
Brian
