### ISSUE TITLE
Inabiltiy to use int.MaxValue in Randomizer.Number

### ISSUE THREAD

**Issue by ixSci** [bchavez/Bogus#30]
The API documentation says that Randomizer.Number accepts inclusive range of (min, max) but it won't work with int.MaxValue for obvious reason. So, in my opinion the method documentation should mention it and a proper exception should be thrown because right now the exception is a bit misleading.

**Comment by bchavez** [comment]
Hello. 

I think calling `Random.Number(int.MaxValue)` seems like a common use case. I'm not particularly fond of `throw` on `int.MaxValue` because then in order to get the same kind of semantic behavior you'd have to do this every time: `Random.Number(int.MaxValue - 1)`. That `- 1` is a bit tacky for me API wise.

So, how about we clamp the value with something semantically similar to `var upper = max == int.MaxValue ? max : max + 1` and add some docs if `max` is `int.MaxValue` then `MaxValue` is exclusive.

Would that work okay for you?
-Brian

**Comment by ixSci** [comment]
Sure, throwing isn't good at all. I've just suggested one of the variants. I like your variant — that will work for me. Still I think the best way would be making the whole thing to match the Random behavior, that is making an upper bound exclusive. It will be kind of a breaking change, though. So I don't know if it is possible or not.

**Comment by bchavez** [comment]
Okay cool. Let's clamp the value. Yea, it would be a breaking change. :disappointed: Hmm. Not sure I like changing the API to `[CanGetThis, ButNotThis)` design either. Maybe it's just me but I still think it makes code easier to reason about with `[CanGetThis, OrThat]` because I always know when I'm dealing with arrays to `.Length - 1`. :sunglasses: 

This is fixed in `/master` now and I'll push out `v7.1.2` in a few minutes when the CI server is done with the build. 

Thanks again for your feedback. I appreciate you taking the time to raise the issue.
-Brian

**Comment by bchavez** [comment]
https://www.nuget.org/packages/Bogus/7.1.2
