### ISSUE TITLE
[Question] Entity Framework and Linking Data

### ISSUE THREAD

**Issue by davidbuckleyni** [bchavez/Bogus#302]
Hi can you provide an example how one would save a password for aspnetuser table using ur functions.
 
Also how does one link tables say you have the order table and order item but you want to link it to specific users for tesitng?.

Is their a way to randomize double amounts for money and how do you tell you say you want 5000 records.

I have a common tennetId which is a guid that must be the same through all the tables for multi user environment is there a way to do that?

**Comment by bchavez** [comment]
Hi David,

My responses to your questions are inline below:

> Hi can you provide an example how one would save a password for aspnetuser table using ur functions.

Saving a password depends on your password implementation. For example, if you use **BCrypt** or `Rfc2898DeriveBytes`/`Pbkdf2` it's probably best to create one shared password hash among all instances, ***for your test data***. Otherwise, creating 5000 or generating a higher number of users may impact performance. For example, generating 1 million unique password hashes with **BCrypt** would probably take a long time.

> Also how does one link tables say you have the order table and order item but you want to link it to specific users for tesitng?.

This would depend on what your C# POCO objects, database tables, and data models look like. What kind of persistence are you using? Legacy ASP.NET Membership Providers? Or ASP.NET Core Identity? Raw ADO.NET? An ORM?

> Is their a way to randomize double amounts for money and how do you tell you say you want 5000 records.

Sure, you can create a random array of double values that look like money. The following example below shows how:
```csharp
void Main()
{
   var f = new Faker();
   var randomDoubles = Enumerable.Range(1,500)
                          .Select(_ => Math.Round(f.Random.Double(7.00d, 99.99d), 2))
                          .ToList();
                          
   randomDoubles.Dump();
}
```

![image](https://user-images.githubusercontent.com/478118/84604640-482ede00-ae4c-11ea-93a9-434a733a6cba.png)

> I have a common tennetId which is a guid that must be the same through all the tables for multi user environment is there a way to do that?

Yes, you can share a common `tenantId` among all your objects. However, many of these questions depend on what your code looks like. As a small example, consider the following:

```csharp
void Main()
{
   var tenantId = Guid.Parse("cf442f33-916f-4767-bb07-bc4733c35a9a");

   var userFaker = new Faker<User>()
      .RuleFor(u => u.TenantId, f => tenantId )
      .RuleFor(u => u.FirstName, f => f.Name.FirstName())
      .RuleFor(u => u.LastName, f => f.Name.LastName());
   
   userFaker.Generate(100).Dump();
}

public class User
{
   public Guid TenantId {get;set;}
   public string FirstName {get;set;}
   public string LastName {get;set;}
}
```
![image](https://user-images.githubusercontent.com/478118/84604873-f424f900-ae4d-11ea-8d81-f975feb4ee9d.png)

----

If you'd like more help, feel free to ask more questions. Also, you can upload a sample project here on GitHub and I can take a more concrete look at what you're trying to achieve and provide additional advice.

I'm going to close the issue now, but feel free to carry on the conversation after this issue is closed.

Thanks,
Brian
