### ISSUE TITLE
RuleForType inference

### ISSUE THREAD

**Issue by weitzhandler** [bchavez/Bogus#305]
When we can `RuleForType` specifying a generic type, we could have the type parameter used from the generic type, so it's redundant.

For example:

```c#
var faker = new Faker<MyClass>()
                      .RuleForType(f => f.Random.Word());
```

I'd be glad to PR this making sure all tests pass plus added tests cases.

Related: #304

**Comment by bchavez** [comment]
Very true. However, the issue resulting from a change like this is that the shorter version would impact readability and involve some compiler magic. Maybe this just comes down to style, but I prefer a little more explicitness in the API than not.

If you prefer your shorter, more terse, version here's how you can achieve it with an extension method:
```csharp
void Main()
{
   var faker = new Faker<MyClass>()
      .RuleForType(typeof(string), f => f.Random.Word())
      .RuleForType(f => f.Random.Int());
      
   faker.Generate().Dump();
}

// Define other methods and classes here
public class MyClass
{
   public string Value1;
   public string Value2;
   public string Value3;
   public string Value4;
   public int ValueA;
   public int ValueB;
   public int ValueC;
}

public static class ExtensionsForFaker
{
   public static Faker<T> RuleForType<T, TType>(this Faker<T> faker, Func<Faker, TType> setterForType)  where T : class
   {
      faker.RuleForType(typeof(TType), setterForType);
      return faker;
   }
}
```
![image](https://user-images.githubusercontent.com/478118/85214205-f63efa00-b31c-11ea-9fc8-0c76437a340e.png)

In most cases, you'd want to rely heavily on and leverage extension methods to fit your API surface style.

Usually, if it can be done somewhat easily with a C# extension method, I defer issues like this to the user rather than making it part of Bogus' core library. If more people run into the same issue, then it can become a candidate for inclusion. I'll keep your suggestion in mind in case others run into the same issue.

**Comment by weitzhandler** [comment]
Thanks for your reply.
