### ISSUE TITLE
Make Clone generic

### ISSUE THREAD

**Issue by vdurante** [bchavez/Bogus#317]
**Context**

I have a Base class, Animal, and 2 inherited classes: Cat and Dog. I want to build a faker for Animal and extend it differently for Cat and Dog

**Alternatives**

Not that I am aware of. I tried to find a way of extracting or exporting the rules and importing it in another Faker, but couldn't find a way of doing so

**Comment by bchavez** [comment]
Hi @vdurante ,

Thank you for posting an issue. I think you'll have to be more specific with what you're looking for.

Can you provide examples of what you're trying to achieve?

Here is an example that seems to satisfy your requirements:

```csharp
void Main()
{
   var dogFaker = new Faker<Dog>()
                      .WithDefaultAnimalRules()
                      .RuleFor(d => d.DogYears, (f, d) => d.Age * 7);
                      
   dogFaker.Generate().Dump();
   
   var oldDogFaker = dogFaker.Clone();
   
   oldDogFaker
      .RuleFor(d => d.DogYears, (f, d) => d.Age * 100);
      
   oldDogFaker.Generate().Dump();
}
```

```csharp
public class Animal
{
   public string Name {get;set;}
   public int Age {get;set;}
}

public class Dog : Animal
{
   public int DogYears {get;set;}
}

public class Cat : Animal
{
   public int CatYears {get;set;}
}

public static class ExtensionsForFakerT
{
   public static Faker<T> WithDefaultAnimalRules<T>(this Faker<T> animalFaker) where T : Animal
   {
      animalFaker
         .RuleFor(u => u.Name, f => f.Name.FirstName())
         .RuleFor(u => u.Age, f => f.Random.Number(1,3));
         
      return animalFaker;
   }
}
```
![image](https://user-images.githubusercontent.com/478118/89970345-80b12500-dc0d-11ea-8d94-b9d7ad0ae8fa.png)

**Comment by vladimir-kovalyuk** [comment]
I would say that the capability requested by @vdurante makes sense. I've found several scenarios in our project where we would like to clone the Faker<T>. For instance 

```
public class FinanceDocument
{
    public ExchangeRate PurchaseRate { get; }

    public ExchangeRate ReimburseRate { get; }
}

```

Where ExchangeRate has its own Faker. In essence there is a need for two different Fakers that are equal but require and **override** for just one property. If Bogus provided support for Override() method it would require much less work to program such scenarios and have better readability (IMHO). Unfortunately quick looking into source code revealed that it is impossible for now because Bogus do not accept Expression<Func>, it accepts Func instead. Which opens possibility for strange issues with captured values of variables at the time of building Faker<T> instead of capturing that variable.

@bchavez  would you consider to switching Faker to Expressions internally instead of Func?
