### ISSUE TITLE
Support c# 9 records

### ISSUE THREAD

**Issue by Trolldemorted** [bchavez/Bogus#334]
Faker only works for types with a parameterless contructor (throwing `No parameterless constructor defined for type 'WASP.Models.Attack'. (System.MissingMethodException)` otherwise).

This makes it impossible to use it with record types which don't have a default constructor. Other dotnet libraries (json parsers, ef core, ...) are able to use the full constructors, so there must be a decent way to do so, could you adapt that?

**Comment by bchavez** [comment]
Hi @Trolldemorted,

Thank you for your issue. What kind of C# 9 support are you specifically looking for from Bogus? Seems C# 9 records work fine? See below:

```csharp
void Main()
{
   var dogFaker = new Faker<Dog>()
                  .CustomInstantiator( f =>
                     new Dog(
                        f.Name.FirstName(),
                        f.Name.LastName()
                      )
                  );
   
   dogFaker.Generate(5).Dump(nameof(dogFaker));

   var catFaker = new Faker<Cat>()
                  .CustomInstantiator(f =>
                     new Cat{
                        FirstName = f.Name.FirstName(),
                        LastName = f.Name.LastName()
                     });

   catFaker.Generate(5).Dump(nameof(catFaker));

   var catFaker2 = new Faker<Cat>()
               .RuleFor(u => u.FirstName, f => f.Name.FirstName())
               .RuleFor(u => u.LastName, f => f.Name.LastName());

   catFaker2.Generate(5).Dump(nameof(catFaker2));
}


public record Dog(string FirstName, string LastName, string Sound = "bark! bark!");
public record Cat
{
   public string FirstName {get; init;}
   public string LastName {get; init;}
   public string Sound {get; } = "prrr! meow!";
}
```

![image](https://user-images.githubusercontent.com/478118/99152709-4023d600-2658-11eb-9eea-1c3fa84a3b27.png)

**Comment by Trolldemorted** [comment]
It is nice to see that it works with CustomInstantiators! I tried with `RuleFor` and it didn't:

```c#
using Bogus;
using System;

namespace BogusRecords
{
    record Dog(string Name);

    class Program
    {
        static void Main()
        {
            var dog = new Faker<Dog>("de")
                .RuleFor(d => d.Name, (f, d) => f.Name.FindName())
                .Generate();
            Console.WriteLine(dog);
        }
    }
}
```

This code throws `System.MissingMethodException: 'No parameterless constructor defined for type 'BogusRecords.Dog'.'`

**Comment by Trolldemorted** [comment]
Thanks for the detailed response! For now, using `CustomInstantiator` will work nicely for us.

Do you know how System.Text.Json and EF Core are handling this? They can construct those records, my first guess was they are assuming that the public properties can be set in a constructor which takes one argument per property.

**Comment by bchavez** [comment]
Hi @Trolldemorted,

No problem. I'm glad I could help.

I'm not sure how `System.Text.Json` or **EF Core** do it. I think you're correct, I'm guessing they probably have some generalized creational object factory that injects values into an object's or record's constructor since constructor parameter argument names match up nicely with property names.

**Comment by Basyras** [comment]
I would like to add my 5 cents here.

I think this is not related just for new **record** feature but any class / struct without parameterless constructor (where we can't add parameterless constructor for many reasons, eg. not having access to the class).

We can use `CustomInstantiator()` as workaround but we loose almost every feature that Bogus provides to us (+ it gets quite annoying to write  `.CustomInstantiator(x=>new MyClass(null,default,null,default))` over and over again)

I would probably suggest creating new method in `Faker<T>` called `SkipContructor()` wich would set `CreateActions[Default]` to `FormatterServices.GetUninitializedObject`.

-  `SkipContructor()` could be called automatically when record or struct is detected in `Faker` constructor).
- Setting `StrictMode(true)` when skipping constructor would also  make sense.

One may argue that skipping constructor is not best practice in normal world (or can even break stuff) but Bogus is already  kinda hacking when fieldInfo.SetValue() is used for every `RuleFor()` (`PopulateAction`) wich use hidden setters (for example every setter of property in records 😉)

I would keep throwing **_No parameterless constructor defined for type_** as default behaivor (By throwing i mean using Activator.CreateInstance() as default CreateActions[Default] ) because constructor could have additional steps necessary for creating a class

@bchavez If you don't have any issues with my suggestions i can make PR for that (probably today).

**Comment by bchavez** [comment]
@Basyras, 

I think adding a method `.SkipConstructor()` probably makes sense. I would probably accept a PR for this. Just make sure there are no changes to the TFMs or any uses of preprocessor directives. Please make as few changes as possible.

Also, at some point (not right now), I'd like to deprecate `.CustomInstantiator()` and rename it to `.UseConstructor()` . In essence, if we think about it:

* `.UseConstructor()` and `.SkipConstructor()` would complement each other well.

However, what I would probably **not** accept is automatically calling `.SkipConstructor()` when `T` is a record. I would need to think about this situation more. As I mentioned earlier, there is no .NET `.IsRecord` in Reflection; so we'd have to rely on a `<Clone>$` hack. I'm very ***wary*** of making too much "automagic" in `Faker<T>`, especially when using a hack for detecting record types.

**Comment by Sharaf-Mansour** [comment]
@Trolldemorted I think an easy way to fix this is just by implementing the default constructor yourself like this
```csharp
public record Dog(string Name)
{
    public Dog() : this(Name: default)
    {

    }
}
```
and that is it.
This will just work fine..
```csharp
var dog = new Faker<Dog>()
    .RuleFor(d => d.Name, f => f.Name.FindName())
    .Generate();
```
Extra..
```csharp
public record Person(string Name, int Age)
{
    public Person() : this(default, default) { }
}
```
and to allow setters 
```csharp
public record Person(string Name, int Age)
{
    public Person() : this(default, default) { }
    public string Name { get; set; } = Name;
    public int Age { get; set; } = Age;
}
```
Hope this helps.

**Comment by PureKrome** [comment]
Just stumbled onto this.. :(

```
public record Foo(int Id);

var foo = new Faker<Foo>().Generate();
```

> System.MissingMethodException : Cannot dynamically create an instance of type 'Foo'. Reason: No parameterless constructor defined.

I have nearly _everything_ defined as `record` ...

Cry.A.Lot. 😿

**Comment by davidandersen** [comment]
Could it be that the single line declaration/constructor of `Foo` removes
the parameterless constructor? If something like below is used, it should
work.

```csharp
public record Foo
{
    public int Id { get; set; }
}
```

Thanks!

**Comment by davidandersen** [comment]
Could it be that the single line declaration/constructor of `Foo` removes the parameterless constructor? If something like below is used, it should work.

```csharp
public record Foo
{
    public int Id { get; set; }
}
```

Thanks!

**Comment by riezebosch** [comment]
> Could it be that the single line declaration/constructor of `Foo` removes the parameterless constructor? If something like below is used, it should work.
> 
> ```cs
> public record Foo
> {
>     public int Id { get; set; }
> }
> ```
> 
> Thanks!

Then your `record` is no longer immutable, plus the notation is much more verbose.
