### ISSUE TITLE
Intellisense Inoperable in VS Code Latest

### ISSUE THREAD

**Issue by pr185193** [bchavez/Bogus#462]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |                 pip install faker latest |
| .NET Core?                   |                 |
| .NET Full Framework?   |                 |
| Windows OS?              |                  |
| Linux OS?                    |                  |
mac
| Visual Studio?              |           1.75.0        |

### What locale are you using with Bogus?
en us

### What's the problem?
intellisense still does not work in VS Code for python faker module

### What possible solutions have you considered?

nuget package is suggested for outdated version?

### Do you have sample code to show what you're trying to do?
```python
# print random name, addr, ipv4
f = Faker()
print(f.name())
```

**Comment by bchavez** [comment]
Hello, thank you for your GH issue.

Bogus is for the .NET runtime and for languages generally well-supported on the .NET runtime by Microsoft: C#, F# and Visual Basic.

I'm not sure how you're using Python with .NET and then attempting to use Bogus. Are you using something like **IronPython**?

If you're using **IronPython**, then I can't help very much because I don't have any experience with **IronPython**. However, if you find the root cause and it is something that we can fix in this repository, then I'll be happy to review anything we might need to change to make Intellisense work better with **IronPython**. Although any fix must not significantly complicate the code base or impact the main C#, F#, and VB languages.

Feel free to re-open the issue if you determine a fix may be needed in this repository.

Thanks,  
Brian
