### ISSUE TITLE
bogus is missing NuGet package README file

### ISSUE THREAD

**Issue by lyndaidaii** [bchavez/Bogus#530]
We've noticed that your package on NuGet.org is missing a README file.

  ## Why READMEs are Important
  A README is essential for users to understand your package's purpose and functionality quickly. It's the first thing users see on NuGet.org and helps them decide if your package meets their needs.

  ## Get Started with READMEs

  ### How to Add a README
  If you're new to NuGet READMEs, follow guidance on [how to add one to your package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

  ### How to write high quality of READMEs
  Follow [a blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) with README best practices and a template file to help you get started. 

  ## We Value Your Feedback
  We value your feedback. If you encounter any issues or have suggestions, please reply to this issue.

  Thank you for your contribution to the NuGet community.

**Comment by bchavez** [comment]
Hello, thank you for the suggestion.

However,
* It looks like **NuGet README** renders `CommonMark` not `GitHub Flavored Markdown (GFM)`; and my personal preference is using `GFM` over `CommonMark`.
* The current README for this NuGet package is here: https://github.com/bchavez/Bogus/blob/master/README.md
  * and is **_good enough_** (and prefer it over a **NuGet README**) because if there's any issue with the code or documentation, the user is already on GitHub and can file a support or discussion more easily than being on the `nuget.org` website; just like the recent GH Issue and PR:
    * #529
    * #528
  * also, the current README for this repo is probably not compatible with `CommonMark` so there might be some unknown amount of work to make it compatible with `nuget.org` README; which I'm not willing to do.
* I do not want to maintain two READMEs or worry about having them get out of sync.
* Also, it looks like you might be using some kind of automation or bot to massively post across multiple repositories on GitHub:
  * https://github.com/lyndaidaii?tab=overview&from=2024-02-01&to=2024-02-09
![image](https://github.com/bchavez/Bogus/assets/478118/0fd0513c-3ff9-4bd8-b8da-ae218fdb6074)

Finally, I would like to politely ask that you refrain from automated creation of GitHub issues on my code-repository. It is not very personable or sincere asking me to do work this way.

For these reasons I'm going to close this issue as "wontfix"/invalid; but feel free to continue the thread if my assumptions/points are wrong. Thank you.
