### ISSUE TITLE
Define char quantity in random names

### ISSUE THREAD

**Issue by NicolaPicoli** [bchavez/Bogus#63]
It would be very useful if we could insert a parameter to define a maximum and minimum quantity of characters in any object generated.
It would help many in running unit tests!

Thank you very much!
Nicola Picoli

**Comment by bchavez** [comment]
Hi @NicolaPicoli ,

Can you give me a few examples of what you're trying to do?

Thanks,
:cat: :bee: ***["Orange buttercat... Chasing after... The crazy bee..."](https://www.youtube.com/watch?v=4WO4oSsxlKs)***

**Comment by NicolaPicoli** [comment]
Hi @bchavez! 

Some entities have character size validations. For example, FirstName must be a minimum of 3 characters and a maximum of 30 characters.

I would like when creating a random "FirstName" could include the minimum and maximum number of characters, for `example:`
```
var result = new Faker<Customer>()
    .RuleFor(p => p.Name, v => v.Company.CompanyName(0).Length([MIN], [MAX]))
```

Tks!

**Comment by bchavez** [comment]
Hi @NicolaPicoli ,

Thanks for your example. Could you try this:
```
public static class ExtensionsForString
{
    private static Randomizer r = new Randomizer();

    public static string ClampLength(this string str, int? min = null, int? max = null)
    {
        if( max != null && str.Length > max )
        {
            return str.Substring(0, max.Value);
        }
        if( min != null && min > str.Length )
        {
            var missingChars = min - str.Length;
            var fillerChars = r.Replace("".PadRight(missingChars.Value, '?'));
            return str + fillerChars;
        }
        return str;
    }
}
```
```
company.CompanyName(0).ClampLength(12, 15).Dump();
```
Produces:
```
"Mitchell Inc"
"Schultz LLCA"
"Mueller IncR"
"Kreiger and Son"
"Welch IncSPC"
"Bashirian LLC"
"Veum IncVVIP"
"Medhurst Inc"
"Paucek Group"
"Hoppe IncPOF"
"Haley IncRUE"
"Waters Group"
```
I think this is the best we can do. After considering your situation I don't think there's an easy way to do this inside Bogus where we avoid the random filler characters.

The first problem arises where we don't have enough characters to meet the minimum length. What do we do?
* We could query the faker database again with a request to something between `min` and `max` length. **But we can't efficiently without a JSONPath size() filter.** Newtonsoft, IIRC, doesn't support a `size()` JSONPath filter in its query select token. We'd have to read the entire list and keep finding words that would meet the requirement. :(

* Add filler characters like we did above (see `ExtensionsForString`).

If you have other ideas let me know but I don't think we should add this to Bogus since it's not an ideal solution. Some people might not be okay with the random filler characters.

:boom: :fire: ***["Set it ablaze like a candle wick... Light it up, light it up..."](https://www.youtube.com/watch?v=qDcFryDXQ7U)***

**Comment by bchavez** [comment]
Hi @NicolaPicoli ,

I've moved `ClampLength` string extension to `Bogus.Extensions` to help work with strings and fake data. This extension method will be available in the next release.

Thanks,
Brian

:sunglasses: :cloud: ***["I just wanna stay in the sun where I find... I know it's hard sometimes"](https://www.youtube.com/watch?v=Pw-0pbY9JeU)***

**Comment by NicolaPicoli** [comment]
Very Nice... 

Thanks @bchavez !

**Comment by aline-almeida** [comment]
Nevertheless, I think having a max value would be useful. For example for testing layouts where we want to try different lengths. I would like to have this on full names.
