### ISSUE TITLE
Random properties always changing values when Faker<T>.Generate(int) returned IEnumerable is stored as such

### ISSUE THREAD

**Issue by Dayleryn** [bchavez/Bogus#75]
Here's a code sample in the context of a unit test class : 

	[TestClass]
	public class UnitTestClass
	{
		IEnumerable<User> fakeUsers;

		private class User
		{
			public string Name { get; set; }

			public DateTime CreatedAt { get; set; }
		}

		[TestInitialize]
		public void Initialize()
		{
			var userFaker = new Faker<User>()
							.RuleFor(t => t.Name, f => f.Name.FirstName())
							.RuleFor(t => t.CreatedAt, f => f.Date.Recent());

			fakeUsers = userFaker.Generate(3);
	}

When running a unit test from that test class while watching the fakeUsers object, I noticed that the randomly generated values for the Name and CreatedAt would constantly change inbetween each debugging step. This means that the faked objects cannot be used for assertions, as the expected values are unstable and will never match the asserted values.

However, if I store the faked User objects in a List<User> and use LINQ.ToList() on the Generate method's returned IEnumerable, the issue no longer occurs and the random values can be properly used.

**Comment by bchavez** [comment]
Hi @Dayleryn ,

Did you set the `Randomizer.Seed` value?

Secondly, I think the crux of your issue is the deferred execution nature of **LINQ**. You'll need to use `.ToList()` if you want a consistent view of your `User` that can be used in your assertions and your debugging. This is because **LINQ** is using [deferred execution](https://blogs.msdn.microsoft.com/charlie/2007/12/10/linq-and-deferred-execution/) with `IEnumerable` we send back. IE: `IEumerable` isn't evaluated (and consequently the `Faker` rules aren't executed) until the `IEumerable` actually used. Visual Studio gives you a warning about this in the debugger view:

![psp_280](https://user-images.githubusercontent.com/478118/27190709-42956952-51aa-11e7-9303-85da165979b1.png)

I'm a bit busy atm so I'll be able to respond later today. For the time being, I'm going to close this issue since I don't see any real issue here. However, if you find a problem with the source code please feel free to re-open the issue and I'll take a second look.

Thanks,
Brian
:walking_man: :walking_woman: [**Missing Persons - Walking in L.A**](https://www.youtube.com/watch?v=R_UpLtGEWoY)

**Comment by napalm684** [comment]
I would recommend updating the documentation to make this point clearer.  Randomizer and ToList() seem non-optional if you are coding asserts to expect specific values.  I was left scratching my head today wondering why once Generate() was called my values kept changing.

**Comment by bchavez** [comment]
Perhaps we should make `.Generate` call `.ToList` under the covers. Seems a sticking point for new users. 

Maybe there's no real advantage practical advantage to returning a **LINQ**ed `IEnumerable`.

**Comment by napalm684** [comment]
I would be fine with that approach, it is more newbie friendly and hey if it saves typing I am all for it.  Could Generate() be overloaded maybe  i.e.: GenerateLazy() which doesn't call the ToList()?
