### ISSUE TITLE
Would you consider adding a SortCode for banking data?

### ISSUE THREAD

**Issue by cmatskas** [bchavez/Bogus#77]
Although you've very well defined a BIC and an IBAN, I was wondering how easy it would be to get an option to add SortCode (6-digits) which are specific to the UK. 
If not, is there an easy way to achieve this though the existing, built-in APIs?
Thanks for the great effort and tool btw

**Comment by bchavez** [comment]
Hi there @cmatskas ,

Thank you for your suggestion. I'm glad you like **Bogus** :sunglasses:. It should be pretty easy to extend **Bogus**. Also, I'd be happy to accept a PR for your feature so others benefit too.

I'm not fimilar with UK `ShortCode`s but 1) since this is locale specific to the UK and 2) I do not think you would need `locale` JSON extension storage, you can simply implement your `.ShortCode` as an extesion method off the `Finance` data set.

Here is how to do that:

1. Fork and checkout `Bogus`.
1. Run `build restore` in **Command Prompt** inside your fresh checkout before using **Visual Studio**.
1. Open **Visual Studio** and create a new file called `ExtensionsForUnitedKingdom.cs` inside [`Bogus\Extensions` here](https://github.com/bchavez/Bogus/tree/master/Source/Bogus/Extensions):

**ExtensionsForUnitedKingdom.cs**:
```
namespace Bogus.Extensions.UnitedKingdom
{
   public static class ExtensionsForUnitedKingdom
   {
      public static string ShortCode(this Bogus.DataSets.Finance finance)
      {
         //whatever is needed to create a valid shortcode.
      }
   }
}
```
4. Write a unit test in [`Bogus.Tests\DataSetTests\FinanceTest.cs`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/DataSetTests/FinanceTest.cs):

**FinanceTest.cs**:
```
[Fact]
public void can_generate_uk_shortcode()
{
   finance.ShortCode().Should().Be("07-24-15");
}
```

5. Compile with VS. Test with `build test`.
6. If all looks good, `build clean` and then commit your changes to your fork.
7. Finally, send in the PR. :sunglasses: 
8. We'll wait for CI to check the changes. Review the PR and publish.

-------

Once your changes are published on NuGet, you'll add the new `using` statement in your program:

```
using Bogus.Extensions.UnitedKingdom;

var faker = new Faker<BankAccount>()
         .RuleFor( acc => acc.MyUKShortCode, f => f.Finance.ShortCode())
```
and all UK related extension methods light up over Bogus' API.

Hope that helps!
Brian


:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=wOjGmpmvGz8#t=2m)***

**Comment by cmatskas** [comment]
@bchavez this is freaking awesome! Probably the best response to an issue I've ever got. For this alone, I'll spend some time and raise the PR. Thanks again my friend and keep up the great work :) 👍

**Comment by bchavez** [comment]
Hi @cmatskas ,

Good news your feature request for UK banking Short Codes are now available in [**Bogus v19**](https://www.nuget.org/packages/Bogus/19.0.1).

Simply import the `Bogus.Extensions.UnitedKingdom` namespace as described here:
https://github.com/bchavez/Bogus#api-extension-methods

The `.ShortCode()` extension method hangs off the `Finance` data set, so `f => f.Finance.ShortCode()` should just about do it.

Enjoy :)

Thanks,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by Nosmadas** [comment]
How come they're named ShortCodes here? The OP even says SortCode?

Great extension BTW, just a little confused as a consumer.

@bchavez

**Comment by bchavez** [comment]
Hi @Nosmadas,

Thanks for your question. The official API is `ShortCode()` defined here:

https://github.com/bchavez/Bogus/blob/f0c42c05ecaff657bfe4f8c11e8cf04972400c2b/Source/Bogus/Extensions/UnitedKingdom/ExtensionsForUnitedKingdom.cs#L13

My reference to ShortCodes (with an s) in this thread is in the plural form (as a group) and references the ability to generate more than one `ShortCode` with **Bogus**.

Is there something else in the United Kingdom that is also called "ShortCodes" that can cause confusion between ShortCode and ShortCodes?

Thanks,
Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by bchavez** [comment]
Ahhh, now I see. Well, I screwed up that one pretty badly didn't I?

The dyslexia is real. I have no idea why I read "Sort" as "Short" (as in small). Lmao. :smiley: 

My bad. 

I'll rename this API to `SortCode` as originally intended and issue a new release shortly (pun intended). hahaha. :sunglasses: 

Should be in a few hours, currently putting the final touches on some other new features. :+1: 

:crescent_moon: :stars: ***["Nothing good happens past 2am..."](https://www.youtube.com/watch?v=VOlcDBXKhSU)***
