### ISSUE TITLE
Feature: change Color methods to return Windows.UI.Color

### ISSUE THREAD

**Issue by JerryNixon** [bchavez/Bogus#90]
Returning the hex value just means the developer has to convert it. Instead, you can return `Windows.UI.Color` whose `ToString()` will return the hex value for developers wanting that. You can accomplish this by introducing a peer method called `WindowsColor()`, too.

Here is what I use:

````csharp
public static class Extensions
{
    private static (byte A, byte R, byte G, byte B) ParseRGB(this string hex)
    {
        hex = hex.Replace("#", string.Empty);
        hex = (hex.Length == 8) ? hex : hex.PadLeft(8, '0');
        var a = (byte)(Convert.ToUInt32(hex.Substring(0, 2), 16));
        var r = (byte)(Convert.ToUInt32(hex.Substring(2, 2), 16));
        var g = (byte)(Convert.ToUInt32(hex.Substring(4, 2), 16));
        var b = (byte)(Convert.ToUInt32(hex.Substring(6, 2), 16));
        return (a, r, g, b);
    }
    public static Windows.UI.Color ToColor(this (byte A, byte R, byte G, byte B) rgb)
        => Windows.UI.Color.FromArgb(rgb.A, rgb.R, rgb.G, rgb.B);
    public static Windows.UI.Color ToColor(this string hex)
        => hex.ParseRGB().ToColor();
    public static SolidColorBrush ToSolidColorBrush(this string hex)
        => hex.ToColor().ToSolidColorBrush();
    public static SolidColorBrush ToSolidColorBrush(this Windows.UI.Color color)
        => new SolidColorBrush(color);
}
````

**Comment by bchavez** [comment]
Hi @JerryNixon ,

I think this would mean we'd have to take a dependency on `PresentationCore.dll` to return `Windows.UI.Color`. I have a suspicion that probably wouldn't work well on **.NET Core / Linux**. :penguin: :smiley:

I think we'd need better tooling support to determine if we're installing on a platform that has `PresentationCore.dll` available for this to work. I'm open to new ideas if we can do this currently in a maintainable way.

Also, I have a feeling the **Win Forms** people would be upset if they had to reference `PresentationCore.dll` in order to use **Bogus**. :rabbit: 

-Brian

:crystal_ball: :dolls: ***["Magic and technology. Voodoo dolls and chants. Electricity. Were makin weird science..."](https://www.youtube.com/watch?v=Jm-upHSP9KU)***

**Comment by JerryNixon** [comment]
So right. My little helpers will simply have to be in every UWP project using Bogus and using Color. You know what, that's not going to end the world.

**Comment by bchavez** [comment]
Let me know if your WPF **Bogus** extension methods/helpers get bigger. If you find that you are needing a lot more specific **WPF** extension methods as you work with **Bogus**, we could possibly start a satellite extension assembly `Bogus.Extensions.WPF.dll` on NuGet for all things **WPF/Bogus** related.

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***
