### ISSUE TITLE
Fake Activator.CreateInstance

### ISSUE THREAD

**Issue by grahamehorner** [bchavez/Bogus#97]
The Fake[T].cs is not working with Person; this is due to Person not having a default constructor with no parameters; (note: constructor with optional parameters is not the same) and Fake is not passing the locale to the classes; should the code use ?

CreateActions[Default] = faker
=> Activator.CreateInstance(this.FakingType,this.Locale) as T;

instead of  
 => Activator.CreateInstance<T>( )

**Comment by bchavez** [comment]
Hi @grahamehorner ,

First off, thanks for using **Bogus**. I appreciate the issue and always like hearing from devs using **Bogus**.

The `Person` object isn't designed to be used by `Faker<T>` where `T` is `Person` itself. Basically, newing up a `Person` is just a really easy way to get context related fake data about a fake person's identity without having to go through the formal ceremony of building context related rules with `new Faker<T>.Rule*(f => f...)`.  So, the correct way to use `Person` is as follows:
```
var p = new Person()
```
Also, the `Faker` facade, when building `Faker<T>.Rule*(f => f...)` rules does have an `f => f.Person` that is readily available and changes after each generation of `T`; so it's *kind of* redundant to say `new Faker<Person>()`.

Hope that helps. If you'd like to discuss more about your issue feel free to reach out on gitter: https://gitter.im/bchavez/Bogus

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by grahamehorner** [comment]
Sorry but the Issue I was trying to show here is that the Faker code is NOT passing the locale to the T which IMHO it should be to ensure the faked item is an item with the same locale as the Faker ?

**Comment by bchavez** [comment]
Hi @grahamehorner ,

Sorry, I am having trouble understanding what you're trying to advocate. You'll have to post a full working example of code so I can better understand what you're trying to achieve with **Bogus** and show me how the current implementation of **Bogus** isn't working out for you.

**Bogus** is currently designed so that `T` can be any C# class. **Bogus** doesn't make any assumptions about `T`. Same goes for `T`'s constructor and `T`'s constructor arguments. This is a ***deliberate*** design decision.

If you want to pass the `locale` to the object being faked, you'll need to use the `.CustomInstantiator` setup method:

```csharp
void Main()
{
   var faker = new Faker<Order>()
                   .CustomInstantiator(f =>
                   {
                      return new Order(f.Locale);
                   });

   faker.Generate();
}

public class Order
{
   public Order(string localeUsed)
   {
      Console.WriteLine(localeUsed);
   }
}
// OUTPUT: en
```

Otherwise, I think might be asking to have `Faker<T>` "inject" the locale string into `T`'s constructor automatically? like an IoC container? If so, IoC-like behavior is not something I plan support because 1) it's automagical, and 2) it breaks the design goal as stated above. `Faker<T>` is just a wrapper around `T`, not really an IoC container.

**Comment by grahamehorner** [comment]
I'm still a bit confused as you show examples along the lines of 
 
```
var faker = new Faker<TFakeType>("en_GB")
.RuleFor(u => u.POST_TOWN, f => f.Address.City())

```
but the resulting fake given is not using the locale ?

**Comment by bchavez** [comment]
Hi @grahamehorner ,

Yes, when you pass `en_GB`, in the `Faker<>` constructor, the `f => f.Anything..` parameter should be tied to [`en_GB`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/en_GB.locale.json). If the [`en_GB` locale](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/en_GB.locale.json) doesn't have data for the category you are using, then the default fallback [`en` locale](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/en.locale.json) is used.
